import {
  CausalGraph,
  CausalNode,
  CausalEdge,
  CausalShock,
  RiskPropagationCard,
  GraphMetadata,
  OmegaFragilityProfile,
} from "./types";

// ─── Helper ─────────────────────────────────────────────────────
// Pillars: I=Irreplaceability, R=Restoration Latency, J=Jurisdictional Hazard,
//          C=Cascade Load, T=Tail Depth
function omega(
  composite: number,
  irreplaceability: number,
  restorationLatency: number,
  jurisdictionalHazard: number,
  cascadeLoad: number,
  tailDepth: number,
): OmegaFragilityProfile {
  return { composite, irreplaceability, restorationLatency, jurisdictionalHazard, cascadeLoad, tailDepth };
}

// ─── Main Graph Nodes ─────────────────────────────────────
const NODES: CausalNode[] = [
  // ─── Middle East Playbook: Claire Data Collection (65 nodes) ──
  // ── Saudi Aramco Energy (14) ──
  {
    id: "sa_east_west_pipeline",
    label: "East-West Pipeline",
    shortLabel: "EAP",
    category: "infrastructure",
    omegaFragility: omega(7.6, 7.0, 7.5, 7.5, 10, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Long linear asset with pumping-station exposure; strategic bypass route makes it a high-value target",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_ras_tanura_refinery",
    label: "Ras Tanura Refinery",
    shortLabel: "RTR",
    category: "infrastructure",
    omegaFragility: omega(7.8, 9.0, 7.0, 9.5, 6.7, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Coastal concentration risk; missile/drone exposure; terminal and refinery co-location raises system criticality",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_yanbu_refinery",
    label: "Yanbu Refinery",
    shortLabel: "YAR",
    category: "manufacturing",
    omegaFragility: omega(6.1, 6.0, 7.0, 9.0, 4.5, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Coastal asset; exposed to Red Sea shipping/security disruption; aging facility undergoing digital modernization",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_abqaiq_plants",
    label: "Abqaiq Plants",
    shortLabel: "ABP",
    category: "manufacturing",
    omegaFragility: omega(7.8, 9.0, 7.0, 7.5, 7.9, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Critical single-node processing hub; high-value target; aging but heavily digitized facility",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_master_gas_system_mgs",
    label: "Master Gas System (MGS)",
    shortLabel: "MGS",
    category: "infrastructure",
    omegaFragility: omega(7.2, 6.0, 7.5, 7.5, 9.1, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Large geographically dispersed network; expansion execution risk; compressor/pipeline bottlenecks if outages occur",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_fadhili_gas_plant",
    label: "Fadhili Gas Plant",
    shortLabel: "FGP",
    category: "manufacturing",
    omegaFragility: omega(6.7, 6.0, 7.0, 9.5, 6.4, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Concentrated processing hub; expansion execution risk; regional attack risk",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_wasit_gas_plant",
    label: "Wasit Gas Plant",
    shortLabel: "WGP",
    category: "manufacturing",
    omegaFragility: omega(7.2, 8.0, 7.0, 7.5, 6.4, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Coastal and industrial concentration; gas-processing bottleneck risk if trains or feeders fail",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_hawiyah_gas_plant",
    label: "Hawiyah Gas Plant",
    shortLabel: "HGP",
    category: "manufacturing",
    omegaFragility: omega(6.1, 6.0, 7.0, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "High-throughput inland node; field-pressure management and compression reliability matter",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_ras_tanura_terminal",
    label: "Ras Tanura Terminal",
    shortLabel: "RTT",
    category: "infrastructure",
    omegaFragility: omega(7.6, 8.0, 6.5, 9.5, 7.4, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Coastal / terminal concentration; shipping-channel risk; conflict-related strike risk",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_master_gas_system",
    label: "Master Gas System",
    shortLabel: "MGS",
    category: "infrastructure",
    omegaFragility: omega(7.0, 7.0, 5.5, 7.5, 8.9, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "System-wide critical infrastructure; compressor and processing bottlenecks can propagate nationally; cyber/physical disr",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_juaymah_crude_terminal",
    label: "Juaymah Crude Terminal",
    shortLabel: "JCT",
    category: "infrastructure",
    omegaFragility: omega(6.0, 6.0, 6.5, 7.5, 5.5, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Offshore terminal exposure; maritime security and weather exposure; dependent on surrounding port system",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_juaymah_lpg_terminal",
    label: "Juaymah LPG Terminal",
    shortLabel: "JLT",
    category: "infrastructure",
    omegaFragility: omega(5.7, 6.0, 6.5, 7.5, 4.0, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Marine terminal exposure; concentrated within eastern export complex",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_hawiyah_gas_plant_storage_complex",
    label: "Hawiyah Gas Plant / Storage Complex",
    shortLabel: "HGP",
    category: "manufacturing",
    omegaFragility: omega(6.0, 7.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Strategic balancing asset; stress point during summer demand peaks",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "sa_yanbu_ngl_fractionation_complex",
    label: "Yanbu NGL Fractionation Complex",
    shortLabel: "YNF",
    category: "infrastructure",
    omegaFragility: omega(6.8, 8.0, 6.5, 9.0, 4.5, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "2-5 years",
    physicalConstraint: "Red Sea shipping/security exposure; coastal concentration risk",
    domain: "Saudi Aramco Energy",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  // ── QatarEnergy LNG (11) ──
  {
    id: "qe_north_field_gas_field",
    label: "North Field (gas field)",
    shortLabel: "NF(",
    category: "energy",
    omegaFragility: omega(7.5, 9.5, 8.5, 7.5, 5.2, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "5-10 years",
    physicalConstraint: "Single-basin concentration risk; offshore infrastructure exposure; LNG utilization depends on sustained field deliverabi",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_ras_laffan_industrial_city_rlic",
    label: "Ras Laffan Industrial City (RLIC)",
    shortLabel: "RLI",
    category: "manufacturing",
    omegaFragility: omega(7.2, 9.0, 7.0, 7.5, 5.5, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "High concentration of critical export capacity in one industrial city",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_ras_laffan_port",
    label: "Ras Laffan Port",
    shortLabel: "RLP",
    category: "infrastructure",
    omegaFragility: omega(7.2, 8.0, 6.5, 7.5, 6.9, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Port concentration; berth utilization constraints during disruptions; expansion execution risk",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_qatarenergy_lng_export_trains_qatargas_1",
    label: "QatarEnergy LNG export trains (QatarGas) – 14 trains",
    shortLabel: "QLE",
    category: "manufacturing",
    omegaFragility: omega(6.6, 8.0, 5.5, 7.5, 5.2, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "High global share concentration; operational outage triggers major global price effects",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_north_field_expansion_nfe_nfs",
    label: "North Field Expansion (NFE + NFS)",
    shortLabel: "NFE",
    category: "manufacturing",
    omegaFragility: omega(5.8, 6.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Large capital program; schedule risk; geopolitical risk to construction and offtake",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_laffan_refinery_lr1_lr2_merged",
    label: "Laffan Refinery (LR1+LR2 merged)",
    shortLabel: "LR(",
    category: "manufacturing",
    omegaFragility: omega(6.4, 6.0, 7.0, 7.5, 6.4, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Feedstock dependence on North Field gas/condensate; concentrated in RLIC",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_umm_said_mesaieed_refinery",
    label: "Umm Said / Mesaieed refinery",
    shortLabel: "US/",
    category: "manufacturing",
    omegaFragility: omega(6.6, 8.0, 7.0, 7.5, 4.0, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Industrial city concentration; reliance on feedstock pipelines and storage/terminal chain",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_pearl_gtl_plant",
    label: "Pearl GTL plant",
    shortLabel: "PGP",
    category: "manufacturing",
    omegaFragility: omega(5.8, 6.0, 7.0, 7.5, 4.0, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Large integrated facility; gas supply and processing continuity required",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_oryx_gtl_plant",
    label: "Oryx GTL plant",
    shortLabel: "OGP",
    category: "manufacturing",
    omegaFragility: omega(6.0, 7.0, 7.0, 7.5, 4.0, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Facility outage risk; smaller than Pearl but still strategic",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_dolphin_pipeline_gas_exports_to_uae_oman",
    label: "Dolphin Pipeline (gas exports to UAE/Oman)",
    shortLabel: "DP(",
    category: "infrastructure",
    omegaFragility: omega(7.3, 8.0, 7.5, 7.5, 6.4, 7.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Single corridor dependency; outages can trigger LNG backfill shipments",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qe_barzan_gas_plant",
    label: "Barzan Gas Plant",
    shortLabel: "BGP",
    category: "manufacturing",
    omegaFragility: omega(6.1, 6.0, 7.0, 7.5, 5.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "2-5 years",
    physicalConstraint: "Key domestic supply stabilizer; outage tightens domestic demand balance",
    domain: "QatarEnergy LNG",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  // ── QAFCO Fertilizer (19) ──
  {
    id: "qf_qafco_complex",
    label: "Qatar Fertiliser Company (QAFCO) — Mesaieed ammonia & urea complex",
    shortLabel: "QFC",
    category: "manufacturing",
    omegaFragility: omega(7.3, 6.0, 7.0, 7.5, 10, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qafco7_blue_ammonia",
    label: "QAFCO-7 (Blue Ammonia Project) — new ammonia train with CCS (planned)",
    shortLabel: "Q(A",
    category: "manufacturing",
    omegaFragility: omega(6.2, 6.0, 5.5, 7.5, 6.9, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qatar_energy_feedstock",
    label: "QatarEnergy — natural gas supplier (feedstock provider)",
    shortLabel: "Q—N",
    category: "energy",
    omegaFragility: omega(6.2, 6.0, 5.5, 7.5, 6.9, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_north_field_gas",
    label: "Qatar North Field natural gas resource",
    shortLabel: "QNF",
    category: "energy",
    omegaFragility: omega(6.8, 7.5, 8.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_mesaieed_industrial_city",
    label: "Mesaieed Industrial City (MIC)",
    shortLabel: "MIC",
    category: "infrastructure",
    omegaFragility: omega(5.6, 6.0, 5.5, 7.5, 4.5, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_mesaieed_port",
    label: "Port of Mesaieed export gateway",
    shortLabel: "POM",
    category: "infrastructure",
    omegaFragility: omega(6.2, 6.0, 6.5, 7.5, 6.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qafco_urea_product",
    label: "QAFCO urea product stream",
    shortLabel: "QUP",
    category: "manufacturing",
    omegaFragility: omega(7.0, 6.0, 5.5, 7.5, 10, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qafco_ammonia_product",
    label: "QAFCO ammonia product stream",
    shortLabel: "QAP",
    category: "manufacturing",
    omegaFragility: omega(6.3, 6.0, 5.5, 7.5, 7.4, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qatar_melamine_company",
    label: "Qatar Melamine Company (QMC)",
    shortLabel: "QMC",
    category: "manufacturing",
    omegaFragility: omega(5.7, 6.0, 5.5, 7.5, 5.0, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_gulf_formaldehyde_company",
    label: "Gulf Formaldehyde Company (GFC)",
    shortLabel: "GFC",
    category: "manufacturing",
    omegaFragility: omega(5.7, 6.0, 5.5, 7.5, 5.0, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_aqueous_ammonia_facility",
    label: "QAFCO aqueous ammonia facility",
    shortLabel: "QAA",
    category: "manufacturing",
    omegaFragility: omega(5.6, 6.0, 5.5, 7.5, 4.5, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qafco_1_4_site",
    label: "QAFCO 1-4 site",
    shortLabel: "Q1S",
    category: "manufacturing",
    omegaFragility: omega(5.8, 6.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_qafco_5_6_site",
    label: "QAFCO 5-6 site",
    shortLabel: "Q5S",
    category: "manufacturing",
    omegaFragility: omega(5.8, 6.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Qatar",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_strait_of_hormuz",
    label: "Strait of Hormuz",
    shortLabel: "SOH",
    category: "infrastructure",
    omegaFragility: omega(7.2, 8.5, 5.5, 9.0, 6.2, 7.5),
    globalConcentration: "Global",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_india_fertilizer_market",
    label: "India fertilizer import market",
    shortLabel: "IFI",
    category: "finance",
    omegaFragility: omega(4.7, 6.0, 3.0, 3.0, 5.7, 5.0),
    globalConcentration: "100% India",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_brazil_fertilizer_market",
    label: "Brazil fertilizer import market",
    shortLabel: "BFI",
    category: "finance",
    omegaFragility: omega(4.7, 6.0, 3.0, 3.0, 5.7, 5.0),
    globalConcentration: "100% Brazil",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_australia_fertilizer_market",
    label: "Australia fertilizer customer market",
    shortLabel: "AFC",
    category: "finance",
    omegaFragility: omega(4.4, 6.0, 3.0, 3.0, 4.5, 5.0),
    globalConcentration: "100% Australia",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_usa_fertilizer_market",
    label: "United States fertilizer customer market",
    shortLabel: "USF",
    category: "finance",
    omegaFragility: omega(4.4, 6.0, 3.0, 3.0, 4.5, 5.0),
    globalConcentration: "100% United States",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "qf_global_food_prices",
    label: "Global food price / farm-input stress node",
    shortLabel: "GFP",
    category: "economic",
    omegaFragility: omega(6.3, 6.0, 5.5, 6.0, 7.0, 7.0),
    globalConcentration: "Global",
    replacementTime: "3-5 years",
    domain: "QAFCO Fertilizer",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  // ── Ma'aden Phosphate (21) ──
  {
    id: "mn_ma_aden_phosphate_business",
    label: "Ma'aden Phosphate business",
    shortLabel: "MPB",
    category: "manufacturing",
    omegaFragility: omega(7.0, 6.0, 5.5, 7.5, 10, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Exposure to export routes, gas costs, turnaround outages, price cycles",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_phosphate_3_mega_project",
    label: "Phosphate 3 mega project",
    shortLabel: "P3M",
    category: "manufacturing",
    omegaFragility: omega(6.2, 6.0, 5.5, 7.5, 6.9, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Execution risk, capex, technology ramp-up, market downturn risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_wa_ad_al_shamal_phosphate_hub",
    label: "Wa'ad Al Shamal phosphate hub",
    shortLabel: "WAS",
    category: "manufacturing",
    omegaFragility: omega(7.1, 8.0, 7.0, 7.5, 6.2, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Operational concentration risk; utility and water dependence",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_ras_al_khair_phosphate_hub",
    label: "Ras Al Khair phosphate hub",
    shortLabel: "RAK",
    category: "manufacturing",
    omegaFragility: omega(6.5, 6.0, 7.0, 7.5, 6.7, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Port exposure, coastal/weather risk, shipping disruption risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_umm_wu_al_phosphate_mine",
    label: "Umm Wu'al phosphate mine",
    shortLabel: "UWP",
    category: "manufacturing",
    omegaFragility: omega(6.8, 7.5, 8.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Mine disruption, rail disruption, water/power dependency",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_hazm_al_jalamid_phosphate_mine",
    label: "Hazm Al Jalamid phosphate mine",
    shortLabel: "HAJ",
    category: "manufacturing",
    omegaFragility: omega(6.8, 7.5, 8.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Rail bottleneck; upstream mining disruption",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_north_south_railway",
    label: "North-South Railway",
    shortLabel: "NOR",
    category: "infrastructure",
    omegaFragility: omega(6.6, 8.0, 5.5, 7.5, 5.2, 7.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Single-corridor disruption risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_ras_al_khair_ammonia_units",
    label: "Ras Al Khair ammonia units",
    shortLabel: "RAK",
    category: "manufacturing",
    omegaFragility: omega(6.2, 6.0, 5.5, 7.5, 6.9, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Gas availability, process uptime, export market premiums",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_blue_low_carbon_ammonia_export_program",
    label: "Blue / low-carbon ammonia export program",
    shortLabel: "B/L",
    category: "infrastructure",
    omegaFragility: omega(6.1, 6.0, 6.5, 7.5, 5.7, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Demand risk; shipping-risk premium; certification risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_ras_al_khair_dap_plant",
    label: "Ras Al Khair DAP plant",
    shortLabel: "RAK",
    category: "manufacturing",
    omegaFragility: omega(6.6, 6.0, 5.5, 7.5, 8.6, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Plant maintenance outages directly affect export commitments",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_phosphoric_acid_units",
    label: "Phosphoric acid units",
    shortLabel: "PAU",
    category: "manufacturing",
    omegaFragility: omega(5.9, 6.0, 5.5, 7.5, 5.7, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Acid-unit outage can bottleneck finished fertilizer output",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_sulfuric_acid_units",
    label: "Sulfuric acid units",
    shortLabel: "SAU",
    category: "manufacturing",
    omegaFragility: omega(5.8, 6.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Sulfur feedstock cost and supply risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_phosphogypsum_stacks_recycling_complex",
    label: "Phosphogypsum stacks / recycling complex",
    shortLabel: "PS/",
    category: "infrastructure",
    omegaFragility: omega(5.8, 6.0, 5.5, 7.5, 5.2, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Waste accumulation; permitting; technology ramp risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_industrial_water_pipeline_system",
    label: "Industrial water pipeline system",
    shortLabel: "IWP",
    category: "infrastructure",
    omegaFragility: omega(6.1, 6.0, 5.5, 7.5, 6.4, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Water scarcity, utility outage, pipeline failure",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_natural_gas_feedstock_system",
    label: "Natural gas feedstock system",
    shortLabel: "NGF",
    category: "energy",
    omegaFragility: omega(6.1, 6.0, 5.5, 7.5, 6.4, 5.0),
    globalConcentration: "100% Saudi Arabia",
    replacementTime: "3-7 years",
    physicalConstraint: "Gas curtailment raises production costs or reduces output",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_bangladesh_agricultural_development_corp",
    label: "Bangladesh Agricultural Development Corporation (BADC)",
    shortLabel: "BAD",
    category: "infrastructure",
    omegaFragility: omega(6.3, 6.0, 6.5, 5.0, 7.9, 5.0),
    globalConcentration: "100% Bangladesh",
    replacementTime: "3-7 years",
    physicalConstraint: "Import disruption raises crop input costs and food-security stress",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_india_fertilizer_market",
    label: "India fertilizer market",
    shortLabel: "IFM",
    category: "infrastructure",
    omegaFragility: omega(5.2, 6.0, 6.5, 3.0, 5.0, 5.0),
    globalConcentration: "100% India",
    replacementTime: "3-7 years",
    physicalConstraint: "Price volatility and shipping costs strongly affect demand",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_brazil_fertilizer_market",
    label: "Brazil fertilizer market",
    shortLabel: "BFM",
    category: "infrastructure",
    omegaFragility: omega(5.2, 6.0, 6.5, 3.0, 5.0, 5.0),
    globalConcentration: "100% Brazil",
    replacementTime: "3-7 years",
    physicalConstraint: "High freight sensitivity; import dependence",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_african_import_dependent_markets",
    label: "African import-dependent markets",
    shortLabel: "AIM",
    category: "infrastructure",
    omegaFragility: omega(5.5, 6.0, 6.5, 5.0, 5.0, 5.0),
    globalConcentration: "100% Multiple",
    replacementTime: "3-7 years",
    physicalConstraint: "FX weakness + fertilizer prices amplify food insecurity",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_strait_of_hormuz",
    label: "Strait of Hormuz",
    shortLabel: "SOH",
    category: "infrastructure",
    omegaFragility: omega(8.1, 8.5, 5.5, 8.0, 10, 7.5),
    globalConcentration: "100% Oman / Iran",
    replacementTime: "3-7 years",
    physicalConstraint: "Conflict, insurance spikes, closure risk",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
  {
    id: "mn_global_food_price_stress",
    label: "Global food-price stress",
    shortLabel: "GFS",
    category: "economic",
    omegaFragility: omega(6.4, 6.0, 5.5, 6.0, 7.5, 7.0),
    globalConcentration: "Global",
    replacementTime: "3-7 years",
    physicalConstraint: "Triggered by fertilizer outages, export blocks, or gas cost surges",
    domain: "Ma'aden Phosphate",
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
  },
];

// ─── Main Graph Edges ─────────────────────────────────────
const EDGES: CausalEdge[] = [


  // ─── Middle East Playbook Edges (69) ────────────────────────
  // ── Saudi Aramco ──
  { id: "sa_east_west_pipeline__sa_yanbu_refinery", source: "sa_east_west_pipeline", target: "sa_yanbu_refinery", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Enables crude transfer toward west-coast refining/logistics." },
  { id: "sa_abqaiq_plants__sa_ras_tanura_terminal", source: "sa_abqaiq_plants", target: "sa_ras_tanura_terminal", weight: 0.6, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Processes/stabilizes crude that moves to east-coast export terminals." },
  { id: "sa_abqaiq_plants__sa_east_west_pipeline", source: "sa_abqaiq_plants", target: "sa_east_west_pipeline", weight: 0.6, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Abqaiq sits in the eastern production-processing system that can pump crude westward." },
  { id: "sa_fadhili_gas_plant__sa_master_gas_system_mgs", source: "sa_fadhili_gas_plant", target: "sa_master_gas_system_mgs", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Gas plant sends sales gas into the national gas backbone." },
  { id: "sa_wasit_gas_plant__sa_master_gas_system_mgs", source: "sa_wasit_gas_plant", target: "sa_master_gas_system_mgs", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Wasit is explicitly described as part of the MGS." },
  { id: "sa_hawiyah_gas_plant__sa_master_gas_system_mgs", source: "sa_hawiyah_gas_plant", target: "sa_master_gas_system_mgs", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Major gas-processing node in the Saudi system." },
  { id: "sa_ras_tanura_refinery__sa_ras_tanura_terminal", source: "sa_ras_tanura_refinery", target: "sa_ras_tanura_terminal", weight: 0.6, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Refinery and export-terminal location co-exist at Ras Tanura, forming a key coastal node." },
  { id: "sa_fadhili_gas_plant__sa_master_gas_system", source: "sa_fadhili_gas_plant", target: "sa_master_gas_system", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Design capacity feeds national gas network." },
  { id: "sa_wasit_gas_plant__sa_master_gas_system", source: "sa_wasit_gas_plant", target: "sa_master_gas_system", weight: 0.8, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Processes non-associated gas into domestic network." },
  { id: "sa_ras_tanura_terminal__sa_east_west_pipeline", source: "sa_ras_tanura_terminal", target: "sa_east_west_pipeline", weight: 0.5, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "West-coast bypass reduces full reliance on Gulf route." },
  { id: "sa_east_west_pipeline__sa_yanbu_ngl_fractionation_complex", source: "sa_east_west_pipeline", target: "sa_yanbu_ngl_fractionation_complex", weight: 0.6, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "West-coast hydrocarbon movement underpins Red Sea export flexibility." },
  // ── QatarEnergy ──
  { id: "qe_laffan_refinery_lr1_lr2_merged__qe_ras_laffan_port", source: "qe_laffan_refinery_lr1_lr2_merged", target: "qe_ras_laffan_port", weight: 0.6, lag: 1, type: "directed", confidence: 0.8, isInconsistent: false, physicalMechanism: "Refined products export through Ras Laffan." },
  // ── QAFCO ──
  { id: "qf_qatar_energy_feedstock__qf_qafco_complex", source: "qf_qatar_energy_feedstock", target: "qf_qafco_complex", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Natural gas is the primary input for ammonia production, which is then converted to urea." },
  { id: "qf_qafco_complex__qf_qafco7_blue_ammonia", source: "qf_qafco_complex", target: "qf_qafco7_blue_ammonia", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Blue ammonia project expands ammonia capacity and reduces CO2 via CCS." },
  { id: "qf_qafco_complex__qf_strait_of_hormuz", source: "qf_qafco_complex", target: "qf_strait_of_hormuz", weight: 0.6, lag: 1, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Bulk exports from Persian Gulf generally transit the Strait of Hormuz." },
  { id: "qf_qafco_complex__qf_global_food_prices", source: "qf_qafco_complex", target: "qf_global_food_prices", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Urea supply influences farm input costs and yields; disruptions raise food inflation and political r" },
  { id: "qf_north_field_gas__qf_qatar_energy_feedstock", source: "qf_north_field_gas", target: "qf_qatar_energy_feedstock", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "North Field underpins QatarEnergy feedstock availability to domestic gas-based industries." },
  { id: "qf_qatar_energy_feedstock__qf_qafco_ammonia_product", source: "qf_qatar_energy_feedstock", target: "qf_qafco_ammonia_product", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Natural gas is reformed to produce hydrogen for ammonia synthesis." },
  { id: "qf_qafco_ammonia_product__qf_qafco_urea_product", source: "qf_qafco_ammonia_product", target: "qf_qafco_urea_product", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ammonia reacts with CO2 to produce urea; most ammonia is consumed internally." },
  { id: "qf_qafco_urea_product__qf_gulf_formaldehyde_company", source: "qf_qafco_urea_product", target: "qf_gulf_formaldehyde_company", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Urea is one input into UFC-85, which is then added back to urea to improve strength." },
  { id: "qf_qafco_urea_product__qf_qatar_melamine_company", source: "qf_qafco_urea_product", target: "qf_qatar_melamine_company", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Part of the urea stream is thermally decomposed into melamine via the QMC downstream chain." },
  { id: "qf_qafco_complex__qf_mesaieed_industrial_city", source: "qf_qafco_complex", target: "qf_mesaieed_industrial_city", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO operates inside the Mesaieed industrial cluster." },
  { id: "qf_qafco_complex__qf_mesaieed_port", source: "qf_qafco_complex", target: "qf_mesaieed_port", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Physical fertilizer exports move through the Mesaieed port/logistics system." },
  { id: "qf_mesaieed_port__qf_strait_of_hormuz", source: "qf_mesaieed_port", target: "qf_strait_of_hormuz", weight: 0.6, lag: 1, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Most Gulf exports must transit Hormuz to reach global markets." },
  { id: "qf_qafco_urea_product__qf_india_fertilizer_market", source: "qf_qafco_urea_product", target: "qf_india_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "India is a major import market in the global fertilizer system and is named among QAFCO customer geo" },
  { id: "qf_qafco_urea_product__qf_brazil_fertilizer_market", source: "qf_qafco_urea_product", target: "qf_brazil_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Brazil is a large fertilizer importer and exposed to QAFCO-linked nitrogen supply and price conditio" },
  { id: "qf_qafco_urea_product__qf_australia_fertilizer_market", source: "qf_qafco_urea_product", target: "qf_australia_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Australia is explicitly named among QAFCO customer demand geographies." },
  { id: "qf_qafco_urea_product__qf_usa_fertilizer_market", source: "qf_qafco_urea_product", target: "qf_usa_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "USA is explicitly named among QAFCO customer demand geographies." },
  { id: "qf_strait_of_hormuz__qf_qafco_urea_product", source: "qf_strait_of_hormuz", target: "qf_qafco_urea_product", weight: 0.7, lag: 1, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Any partial closure, insecurity, or insurance spike in Hormuz can constrain QAFCO cargo flows." },
  { id: "qf_qafco_urea_product__qf_global_food_prices", source: "qf_qafco_urea_product", target: "qf_global_food_prices", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Nitrogen fertilizer shortages or price spikes raise farm input costs and can reduce yields, feeding " },
  { id: "qf_qafco7_blue_ammonia__qf_qafco_ammonia_product", source: "qf_qafco7_blue_ammonia", target: "qf_qafco_ammonia_product", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO-7 adds new low-carbon ammonia capacity, increasing system redundancy and export potential." },
  { id: "qf_qafco7_blue_ammonia__qf_global_food_prices", source: "qf_qafco7_blue_ammonia", target: "qf_global_food_prices", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Additional ammonia capacity can support future urea expansion and moderate supply tightness over tim" },
  { id: "qf_qafco_complex__qf_qatar_melamine_company", source: "qf_qafco_complex", target: "qf_qatar_melamine_company", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO fully owns QMC." },
  { id: "qf_qafco_complex__qf_gulf_formaldehyde_company", source: "qf_qafco_complex", target: "qf_gulf_formaldehyde_company", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO holds a 70% stake in GFC." },
  { id: "qf_qafco_ammonia_product__qf_aqueous_ammonia_facility", source: "qf_qafco_ammonia_product", target: "qf_aqueous_ammonia_facility", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Part of ammonia output is used to produce aqueous ammonia for NOx reduction applications." },
  { id: "qf_qafco_1_4_site__qf_qafco_urea_product", source: "qf_qafco_1_4_site", target: "qf_qafco_urea_product", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO 1-4 site contributes to aggregate urea output." },
  { id: "qf_qafco_5_6_site__qf_qafco_urea_product", source: "qf_qafco_5_6_site", target: "qf_qafco_urea_product", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "QAFCO 5-6 site contributes to aggregate urea output." },
  { id: "qf_qafco_urea_product__qf_mesaieed_port", source: "qf_qafco_urea_product", target: "qf_mesaieed_port", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Finished urea moves from production/storage to export loading at Mesaieed." },
  { id: "qf_india_fertilizer_market__qf_global_food_prices", source: "qf_india_fertilizer_market", target: "qf_global_food_prices", weight: 0.7, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Large importing markets amplify price shocks when supply is disrupted." },
  { id: "qf_brazil_fertilizer_market__qf_global_food_prices", source: "qf_brazil_fertilizer_market", target: "qf_global_food_prices", weight: 0.7, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Large importing markets amplify global nitrogen price volatility." },
  // ── Ma'aden ──
  { id: "mn_natural_gas_feedstock_system__mn_ras_al_khair_ammonia_units", source: "mn_natural_gas_feedstock_system", target: "mn_ras_al_khair_ammonia_units", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Natural gas is the core input to ammonia production." },
  { id: "mn_umm_wu_al_phosphate_mine__mn_wa_ad_al_shamal_phosphate_hub", source: "mn_umm_wu_al_phosphate_mine", target: "mn_wa_ad_al_shamal_phosphate_hub", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ore from northern deposits feeds phosphate processing." },
  { id: "mn_hazm_al_jalamid_phosphate_mine__mn_ras_al_khair_phosphate_hub", source: "mn_hazm_al_jalamid_phosphate_mine", target: "mn_ras_al_khair_phosphate_hub", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Mine output is linked by rail to Ras Al Khair complex." },
  { id: "mn_north_south_railway__mn_ras_al_khair_phosphate_hub", source: "mn_north_south_railway", target: "mn_ras_al_khair_phosphate_hub", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Rail corridor moves ore/intermediates to export/finishing hub." },
  { id: "mn_wa_ad_al_shamal_phosphate_hub__mn_ras_al_khair_phosphate_hub", source: "mn_wa_ad_al_shamal_phosphate_hub", target: "mn_ras_al_khair_phosphate_hub", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ma'aden says Wa'ad Al Shamal mines/processes while Ras Al Khair finishes/stores/exports." },
  { id: "mn_ras_al_khair_ammonia_units__mn_ras_al_khair_dap_plant", source: "mn_ras_al_khair_ammonia_units", target: "mn_ras_al_khair_dap_plant", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ammonia is a key input into DAP/phosphate fertilizer output." },
  { id: "mn_sulfuric_acid_units__mn_phosphoric_acid_units", source: "mn_sulfuric_acid_units", target: "mn_phosphoric_acid_units", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Sulfuric acid is part of phosphate fertilizer chemistry chain." },
  { id: "mn_phosphoric_acid_units__mn_ras_al_khair_dap_plant", source: "mn_phosphoric_acid_units", target: "mn_ras_al_khair_dap_plant", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Phosphoric acid is a direct DAP intermediate." },
  { id: "mn_ras_al_khair_phosphate_hub__mn_strait_of_hormuz", source: "mn_ras_al_khair_phosphate_hub", target: "mn_strait_of_hormuz", weight: 0.6, lag: 1, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Arabian Gulf fertilizer exports depend on Gulf shipping lanes." },
  { id: "mn_strait_of_hormuz__mn_bangladesh_agricultural_development_corp", source: "mn_strait_of_hormuz", target: "mn_bangladesh_agricultural_development_corp", weight: 0.7, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Shipping disruption can delay contracted fertilizer deliveries." },
  { id: "mn_strait_of_hormuz__mn_india_fertilizer_market", source: "mn_strait_of_hormuz", target: "mn_india_fertilizer_market", weight: 0.7, lag: 2, type: "confounded", confidence: 0.65, isInconsistent: false, physicalMechanism: "Gulf route disruption raises freight cost and delivery time to India." },
  { id: "mn_strait_of_hormuz__mn_brazil_fertilizer_market", source: "mn_strait_of_hormuz", target: "mn_brazil_fertilizer_market", weight: 0.7, lag: 2, type: "confounded", confidence: 0.65, isInconsistent: false, physicalMechanism: "Long-haul fertilizer exports still depend on Gulf maritime access." },
  { id: "mn_strait_of_hormuz__mn_african_import_dependent_markets", source: "mn_strait_of_hormuz", target: "mn_african_import_dependent_markets", weight: 0.7, lag: 2, type: "confounded", confidence: 0.65, isInconsistent: false, physicalMechanism: "Insurance and freight spikes increase landed fertilizer prices." },
  { id: "mn_ras_al_khair_dap_plant__mn_bangladesh_agricultural_development_corp", source: "mn_ras_al_khair_dap_plant", target: "mn_bangladesh_agricultural_development_corp", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ma'aden renewed a 600,000-ton fertilizer supply agreement with BADC." },
  { id: "mn_bangladesh_agricultural_development_corp__mn_ma_aden_phosphate_business", source: "mn_bangladesh_agricultural_development_corp", target: "mn_ma_aden_phosphate_business", weight: 0.8, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Ma'aden supplies about 42% of Bangladesh's estimated DAP requirement." },
  { id: "mn_ma_aden_phosphate_business__mn_india_fertilizer_market", source: "mn_ma_aden_phosphate_business", target: "mn_india_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "India is a major import market for Gulf phosphate fertilizers." },
  { id: "mn_ma_aden_phosphate_business__mn_brazil_fertilizer_market", source: "mn_ma_aden_phosphate_business", target: "mn_brazil_fertilizer_market", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Brazil is a major global buyer of imported crop nutrients." },
  { id: "mn_ma_aden_phosphate_business__mn_african_import_dependent_markets", source: "mn_ma_aden_phosphate_business", target: "mn_african_import_dependent_markets", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Guide emphasizes Africa as a downstream impact region." },
  { id: "mn_ma_aden_phosphate_business__mn_global_food_price_stress", source: "mn_ma_aden_phosphate_business", target: "mn_global_food_price_stress", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Fertilizer price spikes increase farm input costs and pressure food affordability." },
  { id: "mn_natural_gas_feedstock_system__mn_global_food_price_stress", source: "mn_natural_gas_feedstock_system", target: "mn_global_food_price_stress", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Gas cost spikes raise ammonia and fertilizer prices." },
  { id: "mn_ras_al_khair_ammonia_units__mn_blue_low_carbon_ammonia_export_program", source: "mn_ras_al_khair_ammonia_units", target: "mn_blue_low_carbon_ammonia_export_program", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Low-carbon ammonia is produced at Ras Al Khair and shipped to global markets." },
  { id: "mn_phosphogypsum_stacks_recycling_complex__mn_ma_aden_phosphate_business", source: "mn_phosphogypsum_stacks_recycling_complex", target: "mn_ma_aden_phosphate_business", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "CO2 capture and phosphogypsum recycling aim to lower footprint of phosphate business." },
  { id: "mn_industrial_water_pipeline_system__mn_wa_ad_al_shamal_phosphate_hub", source: "mn_industrial_water_pipeline_system", target: "mn_wa_ad_al_shamal_phosphate_hub", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Water infrastructure supports continuous industrial operations." },
  { id: "mn_industrial_water_pipeline_system__mn_phosphate_3_mega_project", source: "mn_industrial_water_pipeline_system", target: "mn_phosphate_3_mega_project", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Water access is necessary for expansion scaling." },
  { id: "mn_phosphate_3_mega_project__mn_ma_aden_phosphate_business", source: "mn_phosphate_3_mega_project", target: "mn_ma_aden_phosphate_business", weight: 0.6, lag: 1, type: "directed", confidence: 0.7, isInconsistent: false, physicalMechanism: "Project increases phosphate fertilizer production by 50% to 9 Mtpa." },
  { id: "mn_ras_al_khair_dap_plant__mn_global_food_price_stress", source: "mn_ras_al_khair_dap_plant", target: "mn_global_food_price_stress", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Large Gulf fertilizer outages can tighten international supply." },
  { id: "mn_phosphate_3_mega_project__mn_global_food_price_stress", source: "mn_phosphate_3_mega_project", target: "mn_global_food_price_stress", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Expansion is intended to add resilient supply and ease tightness over time." },
  { id: "mn_strait_of_hormuz__mn_global_food_price_stress", source: "mn_strait_of_hormuz", target: "mn_global_food_price_stress", weight: 0.7, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Fertilizer export blockages can transmit into crop-input inflation worldwide." },
  { id: "mn_bangladesh_agricultural_development_corp__mn_global_food_price_stress", source: "mn_bangladesh_agricultural_development_corp", target: "mn_global_food_price_stress", weight: 0.6, lag: 2, type: "temporal", confidence: 0.7, isInconsistent: false, physicalMechanism: "Large fertilizer procurement shocks can affect national crop economics and import bills." },

];

const METADATA: GraphMetadata = {
  density: parseFloat((2 * EDGES.length / (NODES.length * (NODES.length - 1))).toFixed(3)),
  constraintType: "DCD / NOTEARS + PCMCI+ temporal + FCI latent",
  verificationStatus: "UNVERIFIED",
  totalNodes: NODES.length,
  totalEdges: EDGES.length,
  inconsistentEdges: EDGES.filter((e) => e.isInconsistent).length,
  restrictedNodes: NODES.filter((n) => n.isRestricted).length,
};

export const MAIN_GRAPH: CausalGraph = {
  nodes: NODES,
  edges: EDGES,
  metadata: METADATA,
};

export const EMPTY_GRAPH: CausalGraph = {
  nodes: [],
  edges: [],
  metadata: {
    density: 0,
    constraintType: "none",
    verificationStatus: "UNVERIFIED",
    totalNodes: 0,
    totalEdges: 0,
    inconsistentEdges: 0,
    restrictedNodes: 0,
  },
};

// ─── DCD Sub-Graph (for Trinity Panel) ───────────────────────────
export const DCD_NODES: CausalNode[] = NODES.filter(
  (n) => n.discoverySource === "DCD" || n.discoverySource === "merged"
);
export const DCD_EDGES: CausalEdge[] = EDGES.filter(
  (e) =>
    e.type === "directed" &&
    DCD_NODES.some((n) => n.id === e.source) &&
    DCD_NODES.some((n) => n.id === e.target)
);

// ─── PCMCI+ Sub-Graph (temporal) ─────────────────────────────────
export const PCMCI_NODES: CausalNode[] = NODES.filter(
  (n) => n.discoverySource === "PCMCI+" || n.discoverySource === "merged"
);
// Also include nodes that are sources/targets of temporal edges
const temporalEdges = EDGES.filter((e) => e.lag > 0);
const temporalNodeIds = new Set<string>();
temporalEdges.forEach((e) => {
  temporalNodeIds.add(e.source);
  temporalNodeIds.add(e.target);
});
NODES.forEach((n) => {
  if (temporalNodeIds.has(n.id) && !PCMCI_NODES.some((pn) => pn.id === n.id)) {
    PCMCI_NODES.push(n);
  }
});
export const PCMCI_EDGES: CausalEdge[] = EDGES.filter(
  (e) =>
    e.lag > 0 &&
    PCMCI_NODES.some((n) => n.id === e.source) &&
    PCMCI_NODES.some((n) => n.id === e.target)
);

// ─── FCI Sub-Graph (latent confounding) ──────────────────────────
export const FCI_NODES: CausalNode[] = NODES.filter(
  (n) => n.isConfounded || n.discoverySource === "FCI"
);
export const FCI_EDGES: CausalEdge[] = EDGES.filter(
  (e) =>
    e.type === "confounded" ||
    (FCI_NODES.some((n) => n.id === e.source) &&
      FCI_NODES.some((n) => n.id === e.target))
);

// ─── Risk Cards Builder ──────────────────────────────────────────
export function buildRiskCards(
  graph: CausalGraph,
  shocks: CausalShock[]
): RiskPropagationCard[] {
  const totalSeverity = shocks.reduce((sum, s) => sum + s.severity, 0);
  const shockMultiplier = Math.min(1, totalSeverity);

  return graph.nodes
    .map((node) => ({
      nodeId: node.id,
      label: node.label,
      category: node.category,
      omegaScore: parseFloat(
        (node.omegaFragility.composite * (1 + shockMultiplier * 0.05)).toFixed(1)
      ),
      domain: node.domain,
      globalConcentration: node.globalConcentration,
    }))
    .sort((a, b) => b.omegaScore - a.omegaScore)
    .slice(0, 6);
}

// ─── Category Colors ─────────────────────────────────────────────
export function getCategoryColor(category: string): string {
  switch (category) {
    case "manufacturing": return "#00e5ff";
    case "infrastructure": return "#7c4dff";
    case "economic": return "#ffab00";
    case "finance": return "#ff6d00";
    case "energy": return "#00e676";
    case "geopolitical": return "#ff1744";
    case "communications": return "#448aff";
    case "agriculture": return "#76ff03";
    case "science": return "#e040fb";
    default: return "#5a5e72";
  }
}

export function getCategoryLabel(category: string): string {
  return category.toUpperCase();
}

// ─── Domain Colors ───────────────────────────────────────────────
export function getDomainColor(domain: string): string {
  switch (domain) {
    case "Saudi Aramco Energy": return "#00e676";
    case "QatarEnergy LNG": return "#00e5ff";
    case "QAFCO Fertilizer": return "#76ff03";
    case "Ma'aden Phosphate": return "#ffab00";
    default: return "#5a5e72";
  }
}

// ─── Node Domain Map (for cross-domain edge detection) ───────────
export function getNodeDomainMap(): Record<string, string> {
  const map: Record<string, string> = {};
  NODES.forEach((n) => { map[n.id] = n.domain; });
  return map;
}
