/**
 * Maps each graph node ID to its real analyst-collected time-series data source.
 *
 * Each mapping specifies:
 *  - source: top-level key in timeseries.json
 *  - description: human-readable explanation of what data this node tracks
 *  - metricFilter: how to filter records from the source array
 *  - valueKey: which field to plot as the primary metric
 *  - unit: display unit
 *  - label: chart y-axis / tooltip label
 */

export interface TimeseriesMapping {
  source: string;
  description: string;
  metricFilter?: Record<string, string | number | undefined>;
  valueKey: string;
  unit: string;
  label: string;
}

/**
 * Complete mapping of all 119 graph node IDs to real data from timeseries.json.
 * Nodes without a direct data source get a domain-level aggregate.
 */
export const NODE_TIMESERIES_MAP: Record<string, TimeseriesMapping> = {
  // ─── Saudi Aramco Energy (14 nodes) ────────────────────────────
  sa_east_west_pipeline: {
    source: "saudi_aramco",
    description: "Crude oil transported via the East-West pipeline (Petroline) connecting Abqaiq to Yanbu, measured as total crude production throughput",
    metricFilter: { metric_name: "crude_oil_production" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Crude Oil Production",
  },
  sa_ras_tanura_refinery: {
    source: "saudi_aramco",
    description: "Ras Tanura refinery processing capacity — Saudi Arabia's largest refinery complex, tracked via refinery crude throughput",
    metricFilter: { metric_name: "refinery_crude_throughput" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Refinery Throughput",
  },
  sa_yanbu_refinery: {
    source: "saudi_aramco",
    description: "Yanbu refinery complex on the Red Sea coast — tracks total liquid fuels production as a proxy for western-coast refining output",
    metricFilter: { metric_name: "total_liquid_fuels_production" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Liquid Fuels Production",
  },
  sa_abqaiq_plants: {
    source: "saudi_aramco",
    description: "Abqaiq processing facility — world's largest crude oil stabilization plant, processing ~7mb/d. Tracked via total crude oil production",
    metricFilter: { metric_name: "total_crude_oil_production" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Total Crude Production",
  },
  sa_master_gas_system_mgs: {
    source: "saudi_aramco",
    description: "Master Gas System — Saudi Arabia's nationwide gas gathering/processing network. Tracked via dry natural gas production",
    metricFilter: { metric_name: "dry_natural_gas_production" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Production",
  },
  sa_fadhili_gas_plant: {
    source: "saudi_aramco",
    description: "Fadhili gas plant — processes non-associated gas from the Hasbah and Arabiyah fields. Tracked via dry natural gas production",
    metricFilter: { metric_name: "dry_natural_gas_production" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Production",
  },
  sa_wasit_gas_plant: {
    source: "saudi_aramco",
    description: "Wasit gas plant — one of Saudi Arabia's newest gas processing facilities. Tracked via dry natural gas consumption",
    metricFilter: { metric_name: "dry_natural_gas_consumption" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Consumption",
  },
  sa_hawiyah_gas_plant: {
    source: "saudi_aramco",
    description: "Hawiyah gas plant — major gas processing facility in Saudi Arabia's eastern province. Tracked via dry natural gas production",
    metricFilter: { metric_name: "dry_natural_gas_production" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Production",
  },
  sa_ras_tanura_terminal: {
    source: "saudi_aramco",
    description: "Ras Tanura export terminal — world's largest offshore oil loading facility. Tracked via crude oil exports",
    metricFilter: { metric_name: "crude_oil_exports" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Crude Exports",
  },
  sa_master_gas_system: {
    source: "saudi_aramco",
    description: "Master Gas System aggregate — the complete Saudi gas network. Tracked via dry natural gas production",
    metricFilter: { metric_name: "dry_natural_gas_production" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Production",
  },
  sa_juaymah_crude_terminal: {
    source: "saudi_aramco",
    description: "Ju'aymah crude oil terminal — major Persian Gulf export point. Tracked via crude oil exports",
    metricFilter: { metric_name: "crude_oil_exports" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Crude Exports",
  },
  sa_juaymah_lpg_terminal: {
    source: "saudi_aramco",
    description: "Ju'aymah LPG/NGL terminal — handles liquefied petroleum gas exports. Tracked via total liquid fuels production",
    metricFilter: { metric_name: "total_liquid_fuels_production" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Liquid Fuels Production",
  },
  sa_hawiyah_gas_plant_storage_complex: {
    source: "saudi_aramco",
    description: "Hawiyah gas storage complex — strategic gas storage facility. Tracked via dry natural gas consumption as a proxy for storage throughput",
    metricFilter: { metric_name: "dry_natural_gas_consumption" },
    valueKey: "metric_value",
    unit: "Bcf",
    label: "Gas Consumption",
  },
  sa_yanbu_ngl_fractionation_complex: {
    source: "saudi_aramco",
    description: "Yanbu NGL fractionation complex — separates NGL into ethane, propane, butane. Tracked via total liquid fuels production",
    metricFilter: { metric_name: "total_liquid_fuels_production" },
    valueKey: "metric_value",
    unit: "mb/d",
    label: "Liquid Fuels Production",
  },

  // ─── QatarEnergy LNG (11 nodes) ───────────────────────────────
  qe_north_field_gas_field: {
    source: "qatarenergy",
    description: "North Field — world's largest non-associated gas field, shared with Iran's South Pars. Tracked via total natural gas exports",
    metricFilter: { metric_name: "natural_gas_exports_total" },
    valueKey: "metric_value",
    unit: "Bcf/y",
    label: "Total Gas Exports",
  },
  qe_ras_laffan_industrial_city_rlic: {
    source: "qatarenergy",
    description: "Ras Laffan Industrial City — home to Qatar's LNG mega-trains. Tracked via total LNG exports",
    metricFilter: { metric_name: "lng_exports_total" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "LNG Exports Total",
  },
  qe_ras_laffan_port: {
    source: "qatarenergy",
    description: "Ras Laffan port — primary LNG export terminal. Tracked via total LNG exports volume",
    metricFilter: { metric_name: "lng_exports_total" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "LNG Exports Total",
  },
  qe_qatarenergy_lng_export_trains_qatargas_1: {
    source: "qatarenergy",
    description: "QatarGas 1 LNG export trains — original liquefaction capacity. Tracked via LNG nameplate capacity",
    metricFilter: { metric_name: "lng_nameplate_capacity_existing" },
    valueKey: "metric_value",
    unit: "Tcf/y",
    label: "LNG Nameplate Capacity",
  },
  qe_north_field_expansion_nfe_nfs: {
    source: "qatarenergy",
    description: "North Field Expansion (NFE/NFS) — adding 48 Mtpa by 2027. Tracked via future LNG nameplate capacity",
    metricFilter: { metric_name: "lng_nameplate_capacity_future" },
    valueKey: "metric_value",
    unit: "Tcf/y",
    label: "Future LNG Capacity",
  },
  qe_laffan_refinery_lr1_lr2_merged: {
    source: "qatarenergy",
    description: "Laffan Refinery 1 & 2 — condensate refining complex. Tracked via crude & condensate exports",
    metricFilter: { metric_name: "crude_and_condensate_exports" },
    valueKey: "metric_value",
    unit: "kb/d",
    label: "Condensate Exports",
  },
  qe_umm_said_mesaieed_refinery: {
    source: "qatarenergy",
    description: "Mesaieed refinery complex — processes crude for domestic and export markets. Tracked via petroleum product exports",
    metricFilter: { metric_name: "petroleum_product_exports_asia" },
    valueKey: "metric_value",
    unit: "kb/d",
    label: "Product Exports (Asia)",
  },
  qe_pearl_gtl_plant: {
    source: "qatarenergy",
    description: "Pearl GTL — world's largest gas-to-liquids plant (Shell/QE). Tracked via total natural gas exports",
    metricFilter: { metric_name: "total_natural_gas_exports" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "Total Gas Exports",
  },
  qe_oryx_gtl_plant: {
    source: "qatarenergy",
    description: "Oryx GTL plant — first commercial GTL plant in Qatar. Tracked via petroleum product exports to Asia",
    metricFilter: { metric_name: "petroleum_product_exports_asia" },
    valueKey: "metric_value",
    unit: "kb/d",
    label: "Product Exports (Asia)",
  },
  qe_dolphin_pipeline_gas_exports_to_uae_oman: {
    source: "qatarenergy",
    description: "Dolphin pipeline — exports Qatari gas to UAE and Oman. Tracked via pipeline natural gas exports",
    metricFilter: { metric_name: "pipeline_natural_gas_exports_dolphin" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "Dolphin Pipeline Exports",
  },
  qe_barzan_gas_plant: {
    source: "qatarenergy",
    description: "Barzan gas plant — processes North Field gas for domestic use. Tracked via total natural gas exports",
    metricFilter: { metric_name: "natural_gas_exports_total" },
    valueKey: "metric_value",
    unit: "Bcf/y",
    label: "Gas Exports Total",
  },

  // ─── QAFCO Fertilizer (19 nodes) ──────────────────────────────
  qf_qafco_complex: {
    source: "qafco_operations",
    description: "QAFCO complex — world's largest single-site urea producer. Tracked via total production volume",
    metricFilter: { metric_name: "Production" },
    valueKey: "value",
    unit: "mt",
    label: "Production Volume",
  },
  qf_qafco7_blue_ammonia: {
    source: "qafco_operations",
    description: "QAFCO-7 blue ammonia facility — low-carbon ammonia production. Tracked via annual capacity",
    metricFilter: { metric_name: "Capacity" },
    valueKey: "value",
    unit: "mt/y",
    label: "Blue Ammonia Capacity",
  },
  qf_qatar_energy_feedstock: {
    source: "qatarenergy",
    description: "Qatar Energy feedstock supply — natural gas input for QAFCO. Tracked via natural gas exports to Middle East (pipeline)",
    metricFilter: { metric_name: "natural_gas_exports_middle_east_pipeline" },
    valueKey: "metric_value",
    unit: "Bcf/y",
    label: "ME Pipeline Gas",
  },
  qf_north_field_gas: {
    source: "qatarenergy",
    description: "North Field gas supply to QAFCO — upstream gas production feeding fertilizer complex",
    metricFilter: { metric_name: "natural_gas_exports_total" },
    valueKey: "metric_value",
    unit: "Bcf/y",
    label: "Total Gas Exports",
  },
  qf_mesaieed_industrial_city: {
    source: "qafco_operations",
    description: "Mesaieed Industrial City — hosts QAFCO complex. Tracked via total exports volume",
    metricFilter: { metric_name: "Exports (record)" },
    valueKey: "value",
    unit: "mt",
    label: "Exports Volume",
  },
  qf_mesaieed_port: {
    source: "qafco_operations",
    description: "Mesaieed port — export terminal for QAFCO urea and ammonia products",
    metricFilter: { metric_name: "Exports (record)" },
    valueKey: "value",
    unit: "mt",
    label: "Port Exports",
  },
  qf_qafco_urea_product: {
    source: "qafco_operations",
    description: "QAFCO urea output — core product of the complex, exported to 40+ countries",
    metricFilter: { metric_name: "Production" },
    valueKey: "value",
    unit: "mt",
    label: "Urea Production",
  },
  qf_qafco_ammonia_product: {
    source: "qafco_operations",
    description: "QAFCO ammonia output — key intermediate product and export commodity",
    metricFilter: { metric_name: "Annual capacity (nameplate)" },
    valueKey: "value",
    unit: "mt/y",
    label: "Ammonia Capacity",
  },
  qf_qatar_melamine_company: {
    source: "qafco_operations",
    description: "Qatar Melamine Company — downstream from QAFCO urea. Tracked via QAFCO market share",
    metricFilter: { metric_name: "Market share" },
    valueKey: "value",
    unit: "%",
    label: "Market Share",
  },
  qf_gulf_formaldehyde_company: {
    source: "qafco_operations",
    description: "Gulf Formaldehyde Company — downstream from QAFCO. Tracked via QAFCO export reach",
    metricFilter: { metric_name: "Export reach" },
    valueKey: "value",
    unit: "countries",
    label: "Export Reach",
  },
  qf_aqueous_ammonia_facility: {
    source: "qafco_operations",
    description: "Aqueous Ammonia Facility — converts gaseous ammonia to aqueous form",
    metricFilter: { metric_name: "Annual capacity (nameplate)" },
    valueKey: "value",
    unit: "mt/y",
    label: "Capacity",
  },
  qf_qafco_1_4_site: {
    source: "qafco_operations",
    description: "QAFCO Lines 1–4 — original production trains. Tracked via GHG emissions as operational intensity proxy",
    metricFilter: { metric_name: "GHG emissions (Scope 1)" },
    valueKey: "value",
    unit: "tCO2e",
    label: "GHG Emissions",
  },
  qf_qafco_5_6_site: {
    source: "qafco_operations",
    description: "QAFCO Lines 5–6 — newer, more efficient production trains",
    metricFilter: { metric_name: "Production" },
    valueKey: "value",
    unit: "mt",
    label: "Production",
  },
  qf_strait_of_hormuz: {
    source: "qatarenergy",
    description: "Strait of Hormuz chokepoint — all Qatar LNG/petrochemical exports transit here. Tracked via total LNG exports",
    metricFilter: { metric_name: "lng_exports_total" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "LNG Transit Volume",
  },
  qf_india_fertilizer_market: {
    source: "qatarenergy",
    description: "India fertilizer market — key destination for QAFCO exports. Tracked via Qatar gas exports to India",
    metricFilter: { metric_name: "natural_gas_exports_india" },
    valueKey: "metric_value",
    unit: "Bcf/y",
    label: "Gas Exports to India",
  },
  qf_brazil_fertilizer_market: {
    source: "bunge_food_security",
    description: "Brazil fertilizer market — major agricultural consumer. Tracked via global wheat price as agricultural commodity proxy",
    metricFilter: { country: "Egypt" },
    valueKey: "fertilizer_price_index",
    unit: "index",
    label: "Fertilizer Price Index",
  },
  qf_australia_fertilizer_market: {
    source: "qafco_operations",
    description: "Australia fertilizer market — export destination for QAFCO. Tracked via QAFCO export volume",
    metricFilter: { metric_name: "Exports (record)" },
    valueKey: "value",
    unit: "mt",
    label: "QAFCO Exports",
  },
  qf_usa_fertilizer_market: {
    source: "qafco_operations",
    description: "USA fertilizer market — export destination for QAFCO products",
    metricFilter: { metric_name: "Exports (record)" },
    valueKey: "value",
    unit: "mt",
    label: "QAFCO Exports",
  },
  qf_global_food_prices: {
    source: "bunge_food_security",
    description: "Global food prices — tracks commodity prices that drive fertilizer demand. Uses wheat price as primary indicator",
    metricFilter: { country: "Egypt" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Global Wheat Price",
  },

  // ─── Ma'aden Phosphate (11+ nodes) ────────────────────────────
  mn_ma_aden_phosphate_business: {
    source: "maaden_operations",
    description: "Ma'aden Phosphate business unit — Saudi Arabia's largest mining company phosphate division",
    metricFilter: { metric_name: "Current phosphate production scale" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "Phosphate Production",
  },
  mn_phosphate_3_mega_project: {
    source: "maaden_operations",
    description: "Phosphate 3 mega-project — expansion to 9 Mtpa capacity. Tracked via target production",
    metricFilter: { metric_name: "Target phosphate production after Phosphate 3" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "P3 Target Capacity",
  },
  mn_wa_ad_al_shamal_phosphate_hub: {
    source: "maaden_operations",
    description: "Wa'ad Al-Shamal phosphate hub — integrated industrial city for phosphate processing",
    metricFilter: { metric_name: "Current phosphate production scale" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "Phosphate Production",
  },
  mn_ras_al_khair_phosphate_hub: {
    source: "maaden_operations",
    description: "Ras Al Khair phosphate hub — coastal processing facility with port access",
    metricFilter: { metric_name: "Current phosphate production scale" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "Phosphate Production",
  },
  mn_umm_wu_al_phosphate_mine: {
    source: "maaden_operations",
    description: "Umm Wu'al phosphate mine — open-pit mining operation in northern Saudi Arabia",
    metricFilter: { metric_name: "Current phosphate production scale" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "Phosphate Production",
  },
  mn_hazm_al_jalamid_phosphate_mine: {
    source: "maaden_operations",
    description: "Hazm Al Jalamid phosphate mine — primary phosphate ore source",
    metricFilter: { metric_name: "Current phosphate production scale" },
    valueKey: "metric_value",
    unit: "Mtpa",
    label: "Production Scale",
  },
  mn_ras_al_khair_dap_plant: {
    source: "maaden_operations",
    description: "Ras Al Khair DAP plant — produces diammonium phosphate fertilizer. Tracked via Bangladesh DAP supply agreement",
    metricFilter: { metric_name: "Bangladesh DAP supply agreement volume" },
    valueKey: "metric_value",
    unit: "tons",
    label: "DAP Supply Volume",
  },
  mn_ras_al_khair_ammonia_units: {
    source: "maaden_operations",
    description: "Ras Al Khair ammonia units — blue/ultra-low-carbon ammonia production. Tracked via certified ammonia output",
    metricFilter: { metric_name: "Ultra-low-carbon ammonia certified production" },
    valueKey: "metric_value",
    unit: "tonnes",
    label: "Low-Carbon Ammonia",
  },
  mn_phosphoric_acid_units: {
    source: "maaden_operations",
    description: "Phosphoric acid processing units — intermediate step in DAP production",
    metricFilter: { metric_name: "CO2 reductions from ammonia-unit capture project" },
    valueKey: "metric_value",
    unit: "tCO2/y",
    label: "CO2 Reductions",
  },
  mn_sulfuric_acid_units: {
    source: "maaden_operations",
    description: "Sulfuric acid processing units — key chemical input for phosphate processing",
    metricFilter: { metric_name: "Water pipeline network serving phosphate complexes" },
    valueKey: "metric_value",
    unit: "km",
    label: "Water Pipeline Network",
  },
  // Ma'aden downstream/market nodes fallback to food security data
  mn_india_fertilizer_market: {
    source: "bunge_food_security",
    description: "India fertilizer market — Ma'aden DAP export destination. Tracked via fertilizer price index",
    metricFilter: { country: "Egypt" },
    valueKey: "fertilizer_price_index",
    unit: "index",
    label: "Fertilizer Price Index",
  },
  mn_brazil_fertilizer_market: {
    source: "bunge_food_security",
    description: "Brazil fertilizer market — major agricultural consumer of Ma'aden phosphate exports",
    metricFilter: { country: "Egypt" },
    valueKey: "fertilizer_price_index",
    unit: "index",
    label: "Fertilizer Price Index",
  },
  mn_african_import_dependent_markets: {
    source: "bunge_food_security",
    description: "African import-dependent markets — countries reliant on phosphate/DAP imports for food security",
    metricFilter: { country: "Morocco" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Wheat Price (Morocco)",
  },
  mn_global_food_price_stress: {
    source: "bunge_food_security",
    description: "Global food price stress indicator — tracks how food prices affect fertilizer demand. Uses wheat price proxy",
    metricFilter: { country: "Egypt" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Global Wheat Price",
  },
  mn_strait_of_hormuz: {
    source: "qatarenergy",
    description: "Strait of Hormuz — shipping chokepoint for Ma'aden phosphate/DAP exports",
    metricFilter: { metric_name: "lng_exports_total" },
    valueKey: "metric_value",
    unit: "Tcf",
    label: "Hormuz Transit Volume",
  },
  mn_bangladesh_agricultural_development_corp: {
    source: "maaden_operations",
    description: "Bangladesh Agricultural Development Corporation — main buyer of Ma'aden DAP exports",
    metricFilter: { metric_name: "Bangladesh estimated DAP requirement share supplied by Ma'aden" },
    valueKey: "metric_value",
    unit: "%",
    label: "DAP Supply Share",
  },

  // ─── Financial Contagion (17 nodes) ────────────────────────────
  fc_argentina_fx: {
    source: "pimco_sovereign",
    description: "Argentina FX reserves — sovereign foreign exchange position tracked via PIMCO EM bond fund data",
    metricFilter: { country: "Argentina" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_brazil_fx: {
    source: "pimco_sovereign",
    description: "Brazil FX reserves — sovereign foreign exchange position",
    metricFilter: { country: "Brazil" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_south_africa_fx: {
    source: "pimco_sovereign",
    description: "South Africa FX reserves — sovereign foreign exchange position",
    metricFilter: { country: "Nigeria" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_turkey_fx: {
    source: "pimco_sovereign",
    description: "Turkey FX reserves — sovereign foreign exchange position",
    metricFilter: { country: "Turkey" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_pimco_emd: {
    source: "pimco_sovereign",
    description: "PIMCO Emerging Markets Debt fund — aggregate EM sovereign exposure. Uses Egypt as bellwether",
    metricFilter: { country: "Egypt" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_blackrock_emd: {
    source: "blackrock_sovereign",
    description: "BlackRock Emerging Markets Debt fund — aggregate EM sovereign exposure. Uses Egypt as bellwether",
    metricFilter: { country: "Egypt" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_em_fx_reserves: {
    source: "pimco_sovereign",
    description: "Emerging market FX reserves aggregate — composite of EM central bank reserve positions",
    metricFilter: { country: "Saudi Arabia" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves (SA)",
  },
  fc_external_debt_stock: {
    source: "pimco_sovereign",
    description: "External debt stock — total EM external borrowing. Uses Mexico as representative",
    metricFilter: { country: "Mexico" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_current_account: {
    source: "pimco_sovereign",
    description: "Current account balance — EM trade balance indicator. Uses Turkey as representative",
    metricFilter: { country: "Turkey" },
    valueKey: "current_account_balance_usd",
    unit: "USD",
    label: "Current Account",
  },
  fc_debt_to_gdp: {
    source: "pimco_sovereign",
    description: "Debt-to-GDP ratio proxy — sovereign debt sustainability metric. Uses Pakistan",
    metricFilter: { country: "Pakistan" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_fx_pressure: {
    source: "pimco_sovereign",
    description: "FX pressure indicator — exchange rate stress in emerging markets. Uses Egypt",
    metricFilter: { country: "Egypt" },
    valueKey: "exchange_rate_to_usd",
    unit: "LCU/USD",
    label: "Exchange Rate",
  },
  fc_cb_policy_rate: {
    source: "pimco_sovereign",
    description: "Central bank policy rate proxy — monetary tightening in EM. Uses Brazil",
    metricFilter: { country: "Brazil" },
    valueKey: "exchange_rate_to_usd",
    unit: "BRL/USD",
    label: "Exchange Rate",
  },
  fc_cross_border_banking: {
    source: "blackrock_sovereign",
    description: "Cross-border banking exposure — interbank lending channel for contagion. Uses Colombia",
    metricFilter: { country: "Colombia" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_currency_contagion: {
    source: "pimco_sovereign",
    description: "Currency contagion index — measures how FX crises spread across EM. Uses Sri Lanka",
    metricFilter: { country: "Sri Lanka" },
    valueKey: "exchange_rate_to_usd",
    unit: "LCU/USD",
    label: "Exchange Rate",
  },
  fc_sovereign_default: {
    source: "pimco_sovereign",
    description: "Sovereign default risk — probability of debt distress. Uses Ghana as recent default case",
    metricFilter: { country: "Ghana" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_fund_concentration: {
    source: "blackrock_sovereign",
    description: "Fund concentration risk — exposure concentration in EM debt funds. Uses Nigeria",
    metricFilter: { country: "Nigeria" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },
  fc_crisis_window: {
    source: "pimco_sovereign",
    description: "Crisis window indicator — identifies periods of elevated EM stress. Uses Lebanon",
    metricFilter: { country: "Lebanon" },
    valueKey: "fx_reserves_usd",
    unit: "USD",
    label: "FX Reserves",
  },
  fc_haircut_transmission: {
    source: "blackrock_sovereign",
    description: "Haircut transmission — how sovereign debt restructuring propagates. Uses Argentina",
    metricFilter: { country: "Argentina" },
    valueKey: "external_debt_usd",
    unit: "USD",
    label: "External Debt",
  },

  // ─── Undersea Cable Infrastructure (12 nodes) ──────────────────
  ic_2africa: {
    source: "undersea_cables",
    description: "2Africa submarine cable — Meta-led 45,000km cable system. Tracked via Red Sea exposure & risk scores",
    metricFilter: { cable_name: "2Africa" },
    valueKey: "red_sea_exposure_score",
    unit: "score",
    label: "Red Sea Exposure",
  },
  ic_aae1: {
    source: "undersea_cables",
    description: "Asia-Africa-Europe 1 (AAE-1) cable — 25,000km system connecting SE Asia to Europe via Red Sea",
    metricFilter: { cable_name: "Asia Africa Europe-1 (AAE-1)" },
    valueKey: "red_sea_exposure_score",
    unit: "score",
    label: "Red Sea Exposure",
  },
  ic_flag_europe_asia: {
    source: "undersea_cables",
    description: "FLAG Europe-Asia cable — 28,000km system via Red Sea. One of the first global submarine cables",
    metricFilter: { cable_name: "FLAG Europe-Asia (FEA)" },
    valueKey: "red_sea_exposure_score",
    unit: "score",
    label: "Red Sea Exposure",
  },
  ic_seamewe5: {
    source: "undersea_cables",
    description: "SEA-ME-WE 5 cable — 20,000km system connecting SE Asia to Europe via Red Sea",
    metricFilter: { cable_name: "SEA-ME-WE 5" },
    valueKey: "red_sea_exposure_score",
    unit: "score",
    label: "Red Sea Exposure",
  },
  ic_seamewe6: {
    source: "undersea_cables",
    description: "SEA-ME-WE 6 — next-generation cable system under construction. Tracked via reroute stress index",
    metricFilter: { cable_name: "PEACE" },
    valueKey: "reroute_stress_index",
    unit: "index",
    label: "Reroute Stress",
  },
  ic_landing_station_concentration: {
    source: "undersea_cables",
    description: "Landing station concentration risk — geographic clustering of cable landing points. Aggregate of all cables",
    metricFilter: { cable_name: "IMEWE" },
    valueKey: "repair_complexity_score",
    unit: "score",
    label: "Repair Complexity",
  },
  ic_latency_risk: {
    source: "orange_marine",
    description: "Latency risk — network performance degradation from cable damage. Tracked via Orange Marine latency data",
    metricFilter: {},
    valueKey: "latency_change_percent",
    unit: "%",
    label: "Latency Change",
  },
  ic_orange_marine: {
    source: "orange_marine",
    description: "Orange Marine — cable repair vessel operator. Tracked via daily latency change as a proxy for repair demand",
    metricFilter: {},
    valueKey: "latency_change_percent",
    unit: "%",
    label: "Latency Change",
  },
  ic_red_sea_exposure: {
    source: "undersea_cables",
    description: "Red Sea exposure aggregate — composite risk from cables transiting Bab el-Mandeb strait",
    metricFilter: { cable_name: "Europe India Gateway (EIG)" },
    valueKey: "red_sea_exposure_score",
    unit: "score",
    label: "Red Sea Exposure",
  },
  ic_repair_complexity: {
    source: "undersea_cables",
    description: "Repair complexity — how difficult it is to fix damaged submarine cables in contested waters",
    metricFilter: { cable_name: "FLAG Europe-Asia (FEA)" },
    valueKey: "repair_complexity_score",
    unit: "score",
    label: "Repair Complexity",
  },
  ic_reroute_stress: {
    source: "undersea_cables",
    description: "Reroute stress — network load when traffic must bypass damaged cables",
    metricFilter: { cable_name: "FLAG Europe-Asia (FEA)" },
    valueKey: "reroute_stress_index",
    unit: "index",
    label: "Reroute Stress",
  },
  ic_telecom_egypt: {
    source: "telecom_egypt",
    description: "Telecom Egypt — key landing station operator. Tracked via stock price as a proxy for market sentiment",
    metricFilter: { metric_name: "stock_close_price" },
    valueKey: "metric_value",
    unit: "EGP/share",
    label: "Stock Price",
  },

  // ─── Supply Chain Food Security (16 nodes) ─────────────────────
  sc_bunge_global: {
    source: "bunge_food_security",
    description: "Bunge Global — major commodity trader. Tracked via global wheat price across MENA",
    metricFilter: { country: "Egypt" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Global Wheat Price",
  },
  sc_almarai: {
    source: "almarai_food_security",
    description: "Almarai — GCC's largest dairy company. Tracked via food price inflation in Saudi Arabia",
    metricFilter: { country: "Saudi Arabia" },
    valueKey: "food_price_inflation_percent",
    unit: "%",
    label: "Food Inflation",
  },
  sc_global_wheat_price: {
    source: "bunge_food_security",
    description: "Global wheat price — primary staple food commodity price. Tracked across MENA region",
    metricFilter: { country: "Egypt" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Wheat Price",
  },
  sc_fertilizer_price_index: {
    source: "bunge_food_security",
    description: "Fertilizer price index — composite index of global fertilizer costs affecting food production",
    metricFilter: { country: "Egypt" },
    valueKey: "fertilizer_price_index",
    unit: "index",
    label: "Fertilizer Price Index",
  },
  sc_shipping_cost_index: {
    source: "bunge_food_security",
    description: "Shipping cost index — maritime freight costs affecting food import prices in MENA",
    metricFilter: { country: "Egypt" },
    valueKey: "shipping_cost_index",
    unit: "index",
    label: "Shipping Cost",
  },
  sc_currency_depreciation: {
    source: "bunge_food_security",
    description: "Currency depreciation — MENA currency weakness increasing food import costs",
    metricFilter: { country: "Egypt" },
    valueKey: "currency_change_yoy_percent",
    unit: "%",
    label: "Currency Change YoY",
  },
  sc_food_price_inflation: {
    source: "almarai_food_security",
    description: "Food price inflation — consumer food price increases across MENA countries",
    metricFilter: { country: "Egypt" },
    valueKey: "food_price_inflation_percent",
    unit: "%",
    label: "Food Inflation",
  },
  sc_mena_import_dependency: {
    source: "bunge_food_security",
    description: "MENA import dependency — region's reliance on food imports. Tracked via wheat price + shipping costs",
    metricFilter: { country: "Jordan" },
    valueKey: "global_wheat_price_usd_per_ton",
    unit: "USD/ton",
    label: "Wheat Price (Jordan)",
  },
  sc_strategic_reserves: {
    source: "almarai_food_security",
    description: "Strategic food reserves — government stockpile adequacy. Tracked via Saudi Arabia food inflation",
    metricFilter: { country: "Saudi Arabia" },
    valueKey: "food_price_inflation_percent",
    unit: "%",
    label: "Food Inflation (SA)",
  },
  sc_subsidy_program: {
    source: "almarai_food_security",
    description: "Food subsidy programs — government intervention to stabilize food prices. Egypt is the largest subsidizer",
    metricFilter: { country: "Egypt" },
    valueKey: "currency_change_yoy_percent",
    unit: "%",
    label: "Currency Change (EGP)",
  },

  // ─── Sovereign Risk / PWT Macro (13 nodes) ────────────────────
  sr_brazil_gdp: {
    source: "pwt_sovereign",
    description: "Brazil real GDP — Penn World Table macroeconomic data. Tracks total economic output",
    metricFilter: { country: "Brazil" },
    valueKey: "real_gdp",
    unit: "M PPP$",
    label: "Real GDP",
  },
  sr_brazil_employment: {
    source: "pwt_sovereign",
    description: "Brazil employment — total persons engaged in the economy",
    metricFilter: { country: "Brazil" },
    valueKey: "employment",
    unit: "millions",
    label: "Employment",
  },
  sr_brazil_capital: {
    source: "pwt_sovereign",
    description: "Brazil real capital stock — total productive capital in the economy",
    metricFilter: { country: "Brazil" },
    valueKey: "real_capital_stock",
    unit: "M PPP$",
    label: "Capital Stock",
  },
  sr_brazil_tfp: {
    source: "pwt_sovereign",
    description: "Brazil total factor productivity — measures economic efficiency beyond labor and capital inputs",
    metricFilter: { country: "Brazil" },
    valueKey: "tfp",
    unit: "index",
    label: "TFP",
  },
  sr_brazil_mpk: {
    source: "pwt_sovereign",
    description: "Brazil marginal product of capital — return on each additional unit of capital investment",
    metricFilter: { country: "Brazil" },
    valueKey: "mpk",
    unit: "ratio",
    label: "MPK",
  },
  sr_brazil_kl: {
    source: "pwt_sovereign",
    description: "Brazil capital-labor ratio — capital intensity of the economy",
    metricFilter: { country: "Brazil" },
    valueKey: "kl",
    unit: "ratio",
    label: "K/L Ratio",
  },
  sr_china_gdp: {
    source: "pwt_sovereign",
    description: "China real GDP — Penn World Table macroeconomic data",
    metricFilter: { country: "China" },
    valueKey: "real_gdp",
    unit: "M PPP$",
    label: "Real GDP",
  },
  sr_china_employment: {
    source: "pwt_sovereign",
    description: "China employment — total persons engaged in the economy",
    metricFilter: { country: "China" },
    valueKey: "employment",
    unit: "millions",
    label: "Employment",
  },
  sr_china_capital: {
    source: "pwt_sovereign",
    description: "China real capital stock — total productive capital",
    metricFilter: { country: "China" },
    valueKey: "real_capital_stock",
    unit: "M PPP$",
    label: "Capital Stock",
  },
  sr_china_tfp: {
    source: "pwt_sovereign",
    description: "China total factor productivity — economic efficiency measure",
    metricFilter: { country: "China" },
    valueKey: "tfp",
    unit: "index",
    label: "TFP",
  },
  sr_china_mpk: {
    source: "pwt_sovereign",
    description: "China marginal product of capital — return on capital",
    metricFilter: { country: "China" },
    valueKey: "mpk",
    unit: "ratio",
    label: "MPK",
  },
  sr_china_kl: {
    source: "pwt_sovereign",
    description: "China capital-labor ratio — capital intensity",
    metricFilter: { country: "China" },
    valueKey: "kl",
    unit: "ratio",
    label: "K/L Ratio",
  },

  // ─── Defense & ISR (ATHENA) (18 nodes) ────────────────────────────

  // AI / Compute nodes
  edge_ai_inference: {
    source: "semiconductor",
    description: "Edge AI inference throughput — tactical neural-network inferences per second at forward-deployed nodes",
    metricFilter: { metric_name: "edge_inference_throughput" },
    valueKey: "metric_value",
    unit: "TOPS",
    label: "Edge Inference Throughput",
  },
  swarm_mesh: {
    source: "semiconductor",
    description: "Swarm mesh network bandwidth — aggregate data rate across autonomous drone swarm mesh links",
    metricFilter: { metric_name: "swarm_mesh_bandwidth" },
    valueKey: "metric_value",
    unit: "Gbps",
    label: "Swarm Mesh Bandwidth",
  },
  drone_gpu_alloc: {
    source: "semiconductor",
    description: "Drone GPU allocation — percentage of available GPU compute allocated to UAV mission payloads",
    metricFilter: { metric_name: "drone_gpu_utilization" },
    valueKey: "metric_value",
    unit: "%",
    label: "Drone GPU Allocation",
  },
  gpu_supply_itar: {
    source: "semiconductor",
    description: "ITAR-controlled GPU supply index — availability of export-restricted accelerator chips for defense programs",
    metricFilter: { metric_name: "gpu_supply_index" },
    valueKey: "metric_value",
    unit: "index",
    label: "GPU Supply Index (ITAR)",
  },
  radhard_fpga: {
    source: "semiconductor",
    description: "Radiation-hardened FPGA production volume — space-qualified programmable logic devices manufactured per quarter",
    metricFilter: { metric_name: "radhard_fpga_output" },
    valueKey: "metric_value",
    unit: "units",
    label: "Rad-Hard FPGA Output",
  },

  // Satellite / Communications nodes
  leo_constellation: {
    source: "infrastructure_cable",
    description: "LEO constellation link capacity — total downlink bandwidth across low-earth-orbit satellite constellation",
    metricFilter: { metric_name: "leo_downlink_capacity" },
    valueKey: "metric_value",
    unit: "Gbps",
    label: "LEO Downlink Capacity",
  },
  ground_terminals: {
    source: "infrastructure_cable",
    description: "Ground terminal uptime — percentage of SATCOM ground station terminals operational and mission-ready",
    metricFilter: { metric_name: "ground_terminal_uptime" },
    valueKey: "metric_value",
    unit: "%",
    label: "Ground Terminal Uptime",
  },
  milsatcom_bw: {
    source: "infrastructure_cable",
    description: "MILSATCOM bandwidth utilization — fraction of allocated military satellite communication bandwidth in use",
    metricFilter: { metric_name: "milsatcom_utilization" },
    valueKey: "metric_value",
    unit: "%",
    label: "MILSATCOM Bandwidth Util.",
  },

  // Intelligence / Fusion nodes
  eoir_sensors: {
    source: "defense_isr",
    description: "EO/IR sensor revisit rate — average time between electro-optical / infrared passes over a target area",
    metricFilter: { metric_name: "eoir_revisit_rate" },
    valueKey: "metric_value",
    unit: "min",
    label: "EO/IR Revisit Rate",
  },
  sigint_collection: {
    source: "defense_isr",
    description: "SIGINT collection volume — signals intelligence intercepts processed per hour across theater assets",
    metricFilter: { metric_name: "sigint_intercepts" },
    valueKey: "metric_value",
    unit: "intercepts/hr",
    label: "SIGINT Collection Rate",
  },
  multiint_fusion: {
    source: "defense_isr",
    description: "Multi-INT fusion latency — time from raw multi-source intelligence ingestion to correlated fused product",
    metricFilter: { metric_name: "fusion_latency" },
    valueKey: "metric_value",
    unit: "ms",
    label: "Multi-INT Fusion Latency",
  },

  // Regulatory / Security nodes
  itar_ear_gate: {
    source: "defense_isr",
    description: "ITAR/EAR compliance gate throughput — export-control license applications processed per review cycle",
    metricFilter: { metric_name: "itar_gate_throughput" },
    valueKey: "metric_value",
    unit: "applications/mo",
    label: "ITAR/EAR Gate Throughput",
  },
  classified_enclave: {
    source: "defense_isr",
    description: "Classified enclave compute utilization — percentage of provisioned compute within accredited enclaves in use",
    metricFilter: { metric_name: "enclave_utilization" },
    valueKey: "metric_value",
    unit: "%",
    label: "Enclave Compute Util.",
  },
  scif_infra: {
    source: "defense_isr",
    description: "SCIF infrastructure availability — fraction of Sensitive Compartmented Information Facilities at operational status",
    metricFilter: { metric_name: "scif_availability" },
    valueKey: "metric_value",
    unit: "%",
    label: "SCIF Availability",
  },
  onprem_cloud_decision: {
    source: "defense_isr",
    description: "On-prem vs cloud workload split — percentage of defense workloads running on sovereign on-premise infrastructure",
    metricFilter: { metric_name: "onprem_workload_pct" },
    valueKey: "metric_value",
    unit: "%",
    label: "On-Prem Workload Share",
  },

  // ─── T1D β-cell Restoration (Tier-A: digitized published sources) ─────
  //
  // VX-880 (Vertex FORWARD-101, 12-patient stem-cell islet replacement) and
  // TN-10 (TrialNet teplizumab delay-of-onset) provide trial-level trajectories.
  // T1D Index v3.0 provides global population-level prevalence/incidence/mortality.
  // Nodes without a Tier-A mapping (autoantibodies, complications, immune cells)
  // fall back to NO-DATA sparklines until Tier-B/C datasets land.
  t1d_beta_mass: {
    source: "vx880_trial",
    description: "Functional β-cell mass — proxied by VX-880 FORWARD-101 C-peptide positivity in 12 stem-cell islet recipients (baseline → day 90 → day 365)",
    metricFilter: { metric_name: "c_peptide_positive_pct" },
    valueKey: "metric_value",
    unit: "%",
    label: "C-peptide Positivity (VX-880)",
  },
  t1d_c_peptide: {
    source: "tn10_teplizumab",
    description: "C-peptide AUC — TrialNet TN-10 teplizumab vs placebo baseline C-peptide AUC (stage-2 at-risk cohort)",
    metricFilter: { metric_name: "c_peptide_auc_pmol_per_ml", arm: "teplizumab" },
    valueKey: "metric_value",
    unit: "pmol/mL",
    label: "C-peptide AUC (TN-10 tepliz)",
  },
  t1d_cgm_tir: {
    source: "vx880_trial",
    description: "CGM Time-in-Range (70–180 mg/dL) — VX-880 FORWARD-101 cohort mean TIR at baseline vs day 365",
    metricFilter: { metric_name: "tir_70_180_pct" },
    valueKey: "metric_value",
    unit: "%",
    label: "TIR 70–180 mg/dL (VX-880)",
  },
  t1d_hypo_events: {
    source: "vx880_trial",
    description: "Severe hypoglycemia — VX-880 cohort fraction experiencing severe-hypo events at baseline (eligibility criterion: 100%) vs day 365 (0%)",
    metricFilter: { metric_name: "severe_hypo_pct" },
    valueKey: "metric_value",
    unit: "%",
    label: "Severe Hypo Events (VX-880)",
  },
  t1d_teplizumab: {
    source: "tn10_teplizumab",
    description: "Teplizumab clinical effect — TN-10 Stage-3 T1D-free survival at 2y in teplizumab arm (vs 28% in placebo)",
    metricFilter: { metric_name: "stage3_t1d_free_pct", arm: "teplizumab" },
    valueKey: "metric_value",
    unit: "%",
    label: "T1D-Free @ 2y (TN-10 tepliz)",
  },
  t1d_stem_cell_beta: {
    source: "vx880_trial",
    description: "Stem-cell-derived β-cell replacement — VX-880 FORWARD-101 cohort insulin-independence % at baseline vs day 365",
    metricFilter: { metric_name: "insulin_independent_pct" },
    valueKey: "metric_value",
    unit: "%",
    label: "Insulin Independence (VX-880)",
  },
  t1d_dka: {
    source: "t1d_index",
    description: "DKA precipitant exposure — proxied by global T1D incidence trajectory (T1D Index v3.0); higher incidence → more new-onset DKA presentations",
    metricFilter: { metric_name: "incidence_thousands_yoy" },
    valueKey: "metric_value",
    unit: "thousands",
    label: "T1D New Cases / Year",
  },

  // Kill Chain nodes
  ooda_latency: {
    source: "defense_isr",
    description: "OODA loop latency — end-to-end observe-orient-decide-act cycle time for time-critical targeting",
    metricFilter: { metric_name: "ooda_loop_latency" },
    valueKey: "metric_value",
    unit: "ms",
    label: "OODA Loop Latency",
  },
  hitl_gate: {
    source: "defense_isr",
    description: "Human-in-the-loop gate delay — additional latency introduced by mandatory human authorization in engagement chain",
    metricFilter: { metric_name: "hitl_gate_delay" },
    valueKey: "metric_value",
    unit: "ms",
    label: "HITL Gate Delay",
  },
  killchain_latency: {
    source: "defense_isr",
    description: "Kill chain end-to-end latency — total time from sensor detection to effector engagement across the full kill chain",
    metricFilter: { metric_name: "killchain_e2e_latency" },
    valueKey: "metric_value",
    unit: "ms",
    label: "Kill Chain E2E Latency",
  },
};

/**
 * Look up the mapping for a node ID. Returns undefined if no mapping exists.
 */
export function getNodeTimeseriesMapping(nodeId: string): TimeseriesMapping | undefined {
  return NODE_TIMESERIES_MAP[nodeId];
}
