// ─── VX-880 Stem-Cell Islet Transplant Flagship Subgraph ───────────
//
// Scope: Vertex VX-880 Phase 1/2 stem-cell-derived islet therapy (first
// T1D restoration program to demonstrate insulin independence post-
// infusion; Reichman et al. NEJM 2023). Unlike the general T1D pathway
// graph in t1d-graph-data.ts, this subgraph centers the **therapy
// intervention** — pre-infusion recipient risk, dose/immunosuppression
// choices, graft biology, and trial-aligned primary/secondary endpoints
// (fasting C-peptide, MMTT AUC, insulin independence, severe hypo).
//
// Literature grounding:
//   · Reichman T et al. NEJM 2023 — VX-880 first-in-human results
//   · Shapiro AMJ et al. NEJM 2000, 2006 — Edmonton protocol & CITR
//   · Ryan EA et al. Diabetes 2005 — 5-yr islet transplant outcomes
//   · Hering BJ et al. Diabetes Care 2016 — CIT-07 pivotal trial
//   · Bottino R et al. Transplantation 2018 — autoimmune recurrence
//   · Nepom GT / Pugliese A — HLA-DR3/DR4 risk in T1D recurrence
//   · Vigersky R, Battelino T 2019 — TIR ↔ HbA1c coupling (r² ≈ 0.80)
//   · DCCT/EDIC — glycemic legacy effect on complications
//
// All weights are in [0,1]. Edges representing *protective* effects
// carry negative weights (convention matches t1d-graph-data.ts);
// the cascade simulator clamps intensities to [0,1], so negative
// weights principally carry semantic meaning for the copilot and
// downstream estimators rather than altering cascade propagation.
//
// Nodes are tagged category: "science" and domain: "T1D VX-880".
// The T1D brand color (#40c4ff) carries through so they render
// consistently with the general T1D graph in mixed-domain views.

import type {
  CausalGraph,
  CausalNode,
  CausalEdge,
  OmegaFragilityProfile,
} from "./types";

function omega(
  composite: number,
  irreplaceability: number,
  restorationLatency: number,
  jurisdictionalHazard: number,
  cascadeLoad: number,
  tailDepth: number,
): OmegaFragilityProfile {
  return {
    composite,
    irreplaceability,
    restorationLatency,
    jurisdictionalHazard,
    cascadeLoad,
    tailDepth,
  };
}

const VX880_COLOR = "#40c4ff";
const DOMAIN = "T1D VX-880";

// ─── Nodes ──────────────────────────────────────────────────────────
const NODES: CausalNode[] = [
  // ─── Pre-infusion recipient risk ────────────────────────────────
  {
    id: "vx880_hla_risk",
    label: "HLA-DR3/DR4 Risk Alleles",
    shortLabel: "HLA-R",
    category: "science",
    omegaFragility: omega(6.3, 10.0, 10.0, 2.0, 5.0, 3.0),
    globalConcentration: "~50% of T1D carry DR3/DR4; each allele ≈2-3× recurrence hazard in islet transplant",
    replacementTime: "Genetic — unmodifiable",
    physicalConstraint: "Fixed at conception; dictates antigen-presentation repertoire for islet-reactive T cells",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_autoantibody_load",
    label: "Pre-Infusion Islet Autoantibody Titer (GADA/IA-2A/ZnT8A)",
    shortLabel: "Auto-Ab",
    category: "science",
    omegaFragility: omega(6.8, 8.0, 9.0, 3.0, 7.0, 6.0),
    globalConcentration: "Persistent seropositivity in >60% of islet-transplant recipients; predicts recurrence",
    replacementTime: "Years — titers may decline under IS but rarely serorevert",
    physicalConstraint: "B-cell memory survives standard induction regimens (rituximab only partially effective)",
    domain: DOMAIN,
    discoverySource: "FCI",
    isConfounded: true,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_residual_beta",
    label: "Pre-Infusion Residual β-cell Function",
    shortLabel: "β-base",
    category: "science",
    omegaFragility: omega(6.8, 9.0, 9.0, 4.0, 6.0, 5.0),
    globalConcentration: "VX-880 inclusion typically requires near-zero C-peptide (<0.1 ng/mL) — minimal baseline",
    replacementTime: "N/A — baseline measurement",
    physicalConstraint: "Detection floor ~0.02 nmol/L; stimulated >fasting measurement",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_hypo_history",
    label: "Baseline Severe Hypo / Unawareness",
    shortLabel: "Hypo-bl",
    category: "science",
    omegaFragility: omega(4.3, 5.0, 3.0, 2.0, 4.0, 7.0),
    globalConcentration: "VX-880 inclusion: ≥2 severe hypo events/yr or documented hypoglycemia unawareness",
    replacementTime: "Months — unawareness can partially reverse with glucose restoration",
    physicalConstraint: "Counter-regulatory defect persists weeks–months post-restoration",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },

  // ─── Intervention ──────────────────────────────────────────────
  {
    id: "vx880_dose",
    label: "VX-880 Infusion Dose (cells/kg)",
    shortLabel: "Dose",
    category: "science",
    omegaFragility: omega(8.5, 9.0, 10.0, 9.0, 9.0, 6.0),
    globalConcentration: "Single commercial source (Vertex); trial-only access; cell-line IP exclusivity",
    replacementTime: "Re-infusion is possible but constrained by supply + IS re-induction risk",
    physicalConstraint: "Half-dose vs full-dose cohorts show dose-dependent engraftment (Reichman 2023)",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_immunosuppression",
    label: "Immunosuppression Regimen (ATG + Tacrolimus + MMF/Sirolimus)",
    shortLabel: "IS",
    category: "science",
    omegaFragility: omega(6.0, 5.0, 4.0, 6.0, 8.0, 6.0),
    globalConcentration: "Edmonton-derived regimen + ATG induction; standard across islet transplant programs",
    replacementTime: "Reversible — taperable under monitoring",
    physicalConstraint: "Therapeutic window narrow — under-suppress → rejection; over-suppress → infection/malignancy",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },

  // ─── Peri-infusion graft biology ───────────────────────────────
  {
    id: "vx880_ibmir",
    label: "Instant Blood-Mediated Inflammatory Reaction",
    shortLabel: "IBMIR",
    category: "science",
    omegaFragility: omega(6.2, 6.0, 7.0, 4.0, 7.0, 7.0),
    globalConcentration: "Destroys 30-60% of infused islets within hours via platelet/complement activation",
    replacementTime: "Minutes–hours — acute peri-infusion event",
    physicalConstraint: "Intraportal route inherently exposes cells to blood; encapsulation would bypass but is unsolved",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_engraftment",
    label: "Day-30 Engraftment Success",
    shortLabel: "Engraft",
    category: "science",
    omegaFragility: omega(7.8, 8.0, 9.0, 5.0, 9.0, 8.0),
    globalConcentration: "Defined by post-infusion C-peptide rise + graft-function index (BETA-2, SUITO)",
    replacementTime: "Failed engraftment rarely recovers — typically requires re-infusion",
    physicalConstraint: "Hepatic parenchyma oxygen-limited; cell survival bottleneck in first 2 weeks",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_graft_beta_mass",
    label: "Functional Grafted β-cell Mass",
    shortLabel: "β-graft",
    category: "science",
    omegaFragility: omega(8.8, 9.0, 9.0, 7.0, 10.0, 8.0),
    globalConcentration: "The therapy's central effector — every downstream endpoint depends on this node",
    replacementTime: "Years — once destroyed, requires re-infusion + re-induction",
    physicalConstraint: "Terminally differentiated; no endogenous regeneration in adult recipients",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_autoimmune_recur",
    label: "Autoimmune Recurrence (islet-reactive T-cell reactivation)",
    shortLabel: "AI-rec",
    category: "science",
    omegaFragility: omega(7.4, 7.0, 9.0, 3.0, 9.0, 8.0),
    globalConcentration: "Documented in 20-40% of islet-transplant recipients over 5yr (Bottino 2018)",
    replacementTime: "Persistent — memory T cells survive most IS regimens",
    physicalConstraint: "HLA-restricted epitope recognition; re-induction partially effective",
    domain: DOMAIN,
    discoverySource: "FCI",
    isConfounded: true,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_alloimmune_reject",
    label: "Alloimmune Rejection (HLA-mismatch driven)",
    shortLabel: "Allo-rej",
    category: "science",
    omegaFragility: omega(7.5, 7.0, 8.0, 4.0, 9.0, 8.0),
    globalConcentration: "Donor-cell-line HLA mismatch with recipient drives graft loss in IS-tapered patients",
    replacementTime: "Weeks–months once clinically manifest; rescue IS often insufficient",
    physicalConstraint: "Donor-specific antibody formation accelerates under inadequate IS",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },

  // ─── Functional endpoints ──────────────────────────────────────
  {
    id: "vx880_fasting_cpep",
    label: "Fasting C-Peptide",
    shortLabel: "C-pep/f",
    category: "science",
    omegaFragility: omega(5.9, 7.0, 7.0, 2.0, 7.0, 6.0),
    globalConcentration: "Key VX-880 endpoint — primary restoration biomarker",
    replacementTime: "Reflects graft state in real time; responds within days to graft changes",
    physicalConstraint: "Assay floor ~0.02 nmol/L; diurnal variation ±15%",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_mmtt_auc",
    label: "Mixed-Meal C-Peptide AUC (MMTT primary endpoint)",
    shortLabel: "MMTT",
    category: "science",
    omegaFragility: omega(6.1, 7.0, 7.0, 2.0, 8.0, 6.0),
    globalConcentration: "VX-880 primary efficacy endpoint — stimulated β-function capacity",
    replacementTime: "90-min test; results within hours; reflects current graft reserve",
    physicalConstraint: "Requires standardized Boost meal protocol; ±20% inter-visit variability",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_cgm_tir",
    label: "CGM Time-in-Range (70–180 mg/dL)",
    shortLabel: "TIR",
    category: "science",
    omegaFragility: omega(5.1, 5.0, 4.0, 2.0, 7.0, 7.0),
    globalConcentration: "Consensus secondary endpoint; VX-880 responders show >70% TIR post-infusion",
    replacementTime: "Days–weeks to reflect therapy change",
    physicalConstraint: "Sensor MARD ~9-10%; behavioural confounds (meal composition, exercise)",
    domain: DOMAIN,
    discoverySource: "PCMCI+",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_hypo_events",
    label: "Post-Infusion Severe Hypoglycemia Events",
    shortLabel: "Hypo",
    category: "science",
    omegaFragility: omega(5.8, 6.0, 4.0, 3.0, 6.0, 10.0),
    globalConcentration: "Primary safety endpoint — elimination of severe hypo is a headline VX-880 claim",
    replacementTime: "Event-driven; prevention only lever",
    physicalConstraint: "Hypo unawareness persists post-restoration; early counter-regulation imperfect",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_hba1c",
    label: "HbA1c",
    shortLabel: "HbA1c",
    category: "science",
    omegaFragility: omega(4.4, 4.0, 3.0, 2.0, 7.0, 6.0),
    globalConcentration: "Standard glycemic endpoint; ADA target <7% used across trials",
    replacementTime: "Integrates ~90d glycemic exposure; slow response to therapy change",
    physicalConstraint: "Hemoglobin turnover confounded in anemia / hemoglobinopathies",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
  {
    id: "vx880_insulin_indep",
    label: "Insulin Independence",
    shortLabel: "Ins-indep",
    category: "science",
    omegaFragility: omega(4.4, 4.0, 3.0, 2.0, 7.0, 5.0),
    globalConcentration: "Headline VX-880 endpoint; achieved in full-dose cohort by ~90d in Reichman 2023",
    replacementTime: "Binary state; can be lost if graft function declines",
    physicalConstraint: "Threshold definition varies across trials (Ryan criteria, BETA-2 > 15)",
    domain: DOMAIN,
    discoverySource: "merged",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },

  // ─── Safety ────────────────────────────────────────────────────
  {
    id: "vx880_is_toxicity",
    label: "Immunosuppression Toxicity (infection, nephro, malignancy)",
    shortLabel: "IS-tox",
    category: "science",
    omegaFragility: omega(6.7, 6.0, 6.0, 5.0, 8.0, 9.0),
    globalConcentration: "Cumulative IS-attributable adverse events; tacrolimus nephrotoxicity + CMV/BK reactivation leading",
    replacementTime: "Partially reversible with dose reduction; malignancy and advanced CKD irreversible",
    physicalConstraint: "Dose reduction risks rejection — therapeutic trade-off is the central long-term risk",
    domain: DOMAIN,
    discoverySource: "DCD",
    isConfounded: false,
    isRestricted: false,
    datasetColor: VX880_COLOR,
  },
];

// ─── Edges ─────────────────────────────────────────────────────────
const EDGES: CausalEdge[] = [
  // ── Recipient risk → autoimmune recurrence ──
  {
    id: "vx880_e1",
    source: "vx880_hla_risk",
    target: "vx880_autoimmune_recur",
    weight: 0.5,
    lag: 2,
    type: "temporal",
    confidence: 0.75,
    isInconsistent: false,
    physicalMechanism: "DR3/DR4 alleles present islet autoantigens (preproinsulin, GAD65) — HR ~2-3 per risk allele (Nepom/Pugliese)",
    weightSourceRef: "hla-dr-islet-2023",
    confidenceSourceRef: "hla-dr-islet-2023",
  },
  {
    id: "vx880_e2",
    source: "vx880_autoantibody_load",
    target: "vx880_autoimmune_recur",
    weight: 0.6,
    lag: 1,
    type: "temporal",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Pre-existing B-cell memory reactivates upon antigen re-exposure from graft (Bottino 2018)",
  },

  // ── Baseline β → baseline endpoints (additive) ──
  {
    id: "vx880_e3",
    source: "vx880_residual_beta",
    target: "vx880_fasting_cpep",
    weight: 0.3,
    lag: 0,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Pre-infusion endogenous C-peptide contributes additively to post-infusion total",
  },
  {
    id: "vx880_e4",
    source: "vx880_residual_beta",
    target: "vx880_mmtt_auc",
    weight: 0.25,
    lag: 0,
    type: "directed",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Native stimulated response adds to graft-derived MMTT AUC (small in VX-880 inclusion population)",
  },

  // ── Hypo unawareness persistence ──
  {
    id: "vx880_e5",
    source: "vx880_hypo_history",
    target: "vx880_hypo_events",
    weight: 0.4,
    lag: 0,
    type: "directed",
    confidence: 0.75,
    isInconsistent: false,
    physicalMechanism: "Counter-regulatory defect persists weeks post-restoration — early hypo events reflect prior unawareness",
  },

  // ── Intervention → graft biology ──
  {
    id: "vx880_e6",
    source: "vx880_dose",
    target: "vx880_engraftment",
    weight: 0.75,
    lag: 1,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Dose-dependent engraftment: full-dose cohort >> half-dose in Reichman NEJM 2025",
    weightSourceRef: "reichman-nejm-2025",
    confidenceSourceRef: "reichman-nejm-2025",
  },
  {
    id: "vx880_e7",
    source: "vx880_dose",
    target: "vx880_graft_beta_mass",
    weight: 0.8,
    lag: 2,
    type: "temporal",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Direct effector of grafted β-cell mass — infused cells × survival fraction",
  },
  {
    id: "vx880_e8",
    source: "vx880_ibmir",
    target: "vx880_engraftment",
    weight: -0.45,
    lag: 0,
    type: "directed",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Platelet/complement activation destroys 30-60% of islets within hours of intraportal infusion",
  },
  {
    id: "vx880_e9",
    source: "vx880_engraftment",
    target: "vx880_graft_beta_mass",
    weight: 0.9,
    lag: 1,
    type: "directed",
    confidence: 0.9,
    isInconsistent: false,
    physicalMechanism: "Day-30 engraftment defines viable β-cell pool entering steady-state function",
  },

  // ── Immunosuppression → protective + toxic effects ──
  {
    id: "vx880_e10",
    source: "vx880_immunosuppression",
    target: "vx880_autoimmune_recur",
    weight: -0.65,
    lag: 0,
    type: "directed",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Calcineurin inhibition + MMF suppresses T-cell activation — partially blocks recurrence (Bottino 2018)",
  },
  {
    id: "vx880_e11",
    source: "vx880_immunosuppression",
    target: "vx880_alloimmune_reject",
    weight: -0.75,
    lag: 0,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Primary IS role — prevents HLA-mismatch-driven rejection (Edmonton protocol; CIT-07)",
    weightSourceRef: "shapiro-edmonton-2000",
    confidenceSourceRef: "hering-cit07-2016",
  },
  {
    id: "vx880_e12",
    source: "vx880_immunosuppression",
    target: "vx880_is_toxicity",
    weight: 0.7,
    lag: 3,
    type: "temporal",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Dose-dependent cumulative nephrotoxicity (tacrolimus), infection risk (CMV/BK), malignancy (PTLD)",
  },

  // ── Immune attack → graft destruction ──
  {
    id: "vx880_e13",
    source: "vx880_autoimmune_recur",
    target: "vx880_graft_beta_mass",
    weight: -0.7,
    lag: 2,
    type: "temporal",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Islet-reactive T cells recapitulate original disease — slower than alloimmune but harder to control",
  },
  {
    id: "vx880_e14",
    source: "vx880_alloimmune_reject",
    target: "vx880_graft_beta_mass",
    weight: -0.85,
    lag: 1,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Donor-specific antibodies + T-cell-mediated rejection destroy graft within weeks once active",
  },

  // ── Graft → functional endpoints ──
  {
    id: "vx880_e15",
    source: "vx880_graft_beta_mass",
    target: "vx880_fasting_cpep",
    weight: 0.85,
    lag: 0,
    type: "directed",
    confidence: 0.9,
    isInconsistent: false,
    physicalMechanism: "Grafted β-cells secrete insulin + C-peptide 1:1 under basal conditions",
  },
  {
    id: "vx880_e16",
    source: "vx880_graft_beta_mass",
    target: "vx880_mmtt_auc",
    weight: 0.9,
    lag: 0,
    type: "directed",
    confidence: 0.9,
    isInconsistent: false,
    physicalMechanism: "MMTT AUC is the direct readout of stimulated graft β-cell capacity — VX-880 primary endpoint",
  },
  {
    id: "vx880_e17",
    source: "vx880_graft_beta_mass",
    target: "vx880_cgm_tir",
    weight: 0.7,
    lag: 1,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Restored glucose-sensitive insulin secretion reduces glycemic excursions → higher TIR",
  },
  {
    id: "vx880_e18",
    source: "vx880_graft_beta_mass",
    target: "vx880_hypo_events",
    weight: -0.75,
    lag: 1,
    type: "directed",
    confidence: 0.85,
    isInconsistent: false,
    physicalMechanism: "Restored α-cell/β-cell counter-regulation eliminates severe hypo — primary VX-880 safety claim",
  },

  // ── Endpoint → endpoint couplings ──
  {
    id: "vx880_e19",
    source: "vx880_cgm_tir",
    target: "vx880_hba1c",
    weight: -0.8,
    lag: 3,
    type: "temporal",
    confidence: 0.95,
    isInconsistent: false,
    physicalMechanism: "TIR ↔ HbA1c mathematically coupled via time-averaged glucose (Vigersky/Battelino 2019, r²≈0.80)",
    weightSourceRef: "vigersky-2019",
    confidenceSourceRef: "vigersky-2019",
  },
  {
    id: "vx880_e20",
    source: "vx880_fasting_cpep",
    target: "vx880_insulin_indep",
    weight: 0.5,
    lag: 0,
    type: "directed",
    confidence: 0.75,
    isInconsistent: false,
    physicalMechanism: "Fasting C-peptide threshold (BETA-2 component) contributes to independence classification",
  },
  {
    id: "vx880_e21",
    source: "vx880_mmtt_auc",
    target: "vx880_insulin_indep",
    weight: 0.7,
    lag: 0,
    type: "directed",
    confidence: 0.8,
    isInconsistent: false,
    physicalMechanism: "Stimulated C-peptide AUC is the stronger determinant of sustained insulin independence (Ryan criteria)",
    weightSourceRef: "ryan-2005",
    confidenceSourceRef: "ryan-2005",
  },
];

const METADATA = {
  density: EDGES.length / (NODES.length * (NODES.length - 1)),
  constraintType: "VX-880 stem-cell islet transplant trial topology",
  verificationStatus: "UNVERIFIED" as const,
  totalNodes: NODES.length,
  totalEdges: EDGES.length,
  inconsistentEdges: EDGES.filter((e) => e.isInconsistent).length,
  restrictedNodes: NODES.filter((n) => n.isRestricted).length,
};

export const VX880_GRAPH: CausalGraph = {
  nodes: NODES,
  edges: EDGES,
  metadata: METADATA,
};
