-- =============================================================
-- APEX Terminal — API Key Auth (Discovery API)
-- Run this in the Supabase SQL Editor after
-- supabase-discovery-runs.sql.
--
-- Why: gates POST /api/discovery/run + GET /api/discovery/runs(/:id)
-- behind a per-customer API key header. Before this migration, those
-- endpoints accept anonymous requests; anyone with the URL can
-- trigger discovery computations and (after #334) persist arbitrary
-- rows into discovery_runs via the service-role bypass.
--
-- The keys themselves are never stored. We store SHA-256 hashes
-- (key_hash) plus a short non-secret prefix (key_prefix) for
-- support / audit ("the key starting with apx_live_K8qR..."). At
-- validate-time we hash the incoming header and look up by hash.
-- =============================================================

-- 1. API keys table
--
-- Per-customer credentials. A single customer can have multiple
-- active keys (rotation, environment separation). revoked_at is the
-- soft-delete signal; the validator filters keys with revoked_at not
-- null and the row stays for audit.

create table if not exists public.api_keys (
  id           uuid primary key default gen_random_uuid(),
  customer_id  text not null,
  key_hash     text not null unique,
  key_prefix   text not null,
  name         text,
  scopes       text[] not null default array['discovery:read', 'discovery:write']::text[],
  created_at   timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at   timestamptz
);

-- 2. Indexes for the lookup the validator runs every request
--   - key_hash is unique, so the unique index already serves point lookups.
--   - customer_id index supports admin queries ("list keys for customer X").
--   - partial index on active keys keeps the validator's filter cheap.

create index if not exists api_keys_customer_id_idx
  on public.api_keys (customer_id);

create index if not exists api_keys_active_idx
  on public.api_keys (key_hash)
  where revoked_at is null;

-- 3. Row-level security: service-role only
--
-- All access mediated by /api/discovery/* using the service-role
-- key (which bypasses RLS). Anon-key clients hitting api_keys
-- directly see nothing. No customer-facing surface reads this table
-- in v0; key management is admin-only via the Supabase SQL Editor
-- (or a future /admin/keys panel).

alter table public.api_keys enable row level security;

do $$ begin
  create policy "api_keys read by service role only"
    on public.api_keys for select
    using (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "api_keys write by service role only"
    on public.api_keys for all
    using (auth.role() = 'service_role');
exception when duplicate_object then null; end $$;

-- 4. Example bootstrap (commented out — uncomment + edit when issuing
--    the first key). The key string itself is generated by application
--    code (src/lib/discovery/api-key-auth.ts → generateApiKey()) and
--    handed to the customer ONCE. We only persist the hash.
--
-- insert into public.api_keys (customer_id, key_hash, key_prefix, name) values
--   ('demo-customer',
--    '<sha256-hex-of-the-generated-key>',
--    'apx_live_AbCdEfGh',
--    'demo customer cli')
--   on conflict (key_hash) do nothing;
